### ISSUE TITLE
App input does not update when changing apps

### ISSUE THREAD

**Issue by maxileith** [maxileith/homebridge-appletv-enhanced#105]
### Analysis

Currently the active input of the Apple TV accessory does not update when changing apps not via the plugin but another method, e.g. the remote.

### Expected Behavior

Update the active input of the Apple TV accessory.

### Steps To Reproduce

1. Change the input to app A in the Home app via the plugin
2. Navigate with the Apple TV remote to antoher app B and start a movie or something similar
3. The active input is not updated to app B

### Logs

```Markdown
-
```

### Configuration

```JSON
-
```

### Environment

- OS: Raspberry Pi OS Bookworm 12 64-bit
- Docker: false
- Homebridge: 1.7.0
- Apple TV Enhanced: 0.7.0-0
- Node: 20.10.0
- npm: 9.8.1
- Python: 3.11.6

**Comment by maxileith** [comment]
The root cause of this bug is in the pyatv library. I have already created a PR to fix this issue: https://github.com/postlund/pyatv/pull/2300.

**Comment by maxileith** [comment]
Fixed in v1.0.0-2

**Comment by snoslicer8** [comment]
Do you have any suggestions if I am seeing the behavior described in this issue with a brand new install of your plugin today?

On the two Apple TV devices I’ve set up so far, I can change the App on the Apple TV with the plugin and the “Input” in the Home app changes accordingly. If I change the app using the remote (backing out to Home and opening a new app), the active “Input” for the plugin does not change in the Home app. I’ve looked in the logs, and I do not see any updates from this plugin immediately following doing this physical remote action.
