### ISSUE TITLE
STOPPED state is never triggered.

### ISSUE THREAD

**Issue by gd510** [maxileith/homebridge-appletv-enhanced#106]
### Analysis

STOPPED state is never triggered. When I jump out of video playback, in any app, it triggers a 'paused' state and 'music' media type. See screenshot.
<img width="1078" alt="Screenshot 2023-12-04 at 8 26 10 PM" src="https://github.com/maxileith/homebridge-appletv-enhanced/assets/2985505/be95f981-af00-4980-afd1-cc664359db8a">

### Expected Behavior

STOPPED state is triggered when media playback is stopped or when ATV goes to Home screen.

### Steps To Reproduce

n/a

### Logs

```Markdown
n/a
```

### Configuration

```JSON
{
    "mediaTypes": [
        "music",
        "tv",
        "video"
    ],
    "deviceStates": [
        "idle",
        "paused",
        "playing",
        "stopped"
    ],
    "remoteKeysAsSwitch": [
        "home",
        "pause",
        "play",
        "play_pause",
        "stop",
        "turn_off",
        "turn_on"
    ],
    "customInputURIs": [],
    "discover": {
        "unicast": [],
        "blacklist": [],
        "multicast": true
    },
    "name": "Apple TV Enhanced",
    "avadaKedavraAppAmount": 15,
    "forceVenvRecreate": false,
    "logLevel": 3,
    "platform": "AppleTVEnhanced"
}
```

### Environment

- OS: 17.2
- Docker:
- Homebridge: 1.7
- Apple TV Enhanced: 0.6.1
- Node: 20.10
- npm:
- Python: 3.9.2

**Comment by maxileith** [comment]
@gd510 the current device state is reported by the Apple TV. So if the Apple TV does not reported the state stopped, the plugin won't report that either. I have added the stopped state since it is part of the spec. However, I have never seen this state triggered myself.

So this is a bug that Apple has to fix.

**Comment by gd510** [comment]
@maxileith that makes sense. Thanks for the update. 
Great job on the plugin, by the way. 👍🏻

**Comment by gd510** [comment]
@maxileith quick question.... when would the Idle state usually get reported?

**Comment by maxileith** [comment]
Same as for stopped from my experience. However, also part of the spec ...
