### ISSUE TITLE
Deleted pairing in Apple TV now can't repair.

### ISSUE THREAD

**Issue by Glec6** [maxileith/homebridge-appletv-enhanced#12]
How to repair or unpair to repair device. Tried uninstalling on homebridge plugin, still "detects" then has error. Tried resetting the Apple TV, still same issue. Is there a way to unpair to repair?

**Comment by maxileith** [comment]
To reset the plugin completly, you need to delete the plugin storage folder at `/var/lib/homebridge/appletv-enhanced` assuming your homebridge storage path is `/var/lib/homebridge`.

**Comment by maxileith** [comment]
However, this is definetly a good issue that you are raising here. The plugin should definetly detect when the credentials are not valid anylonger and then initiate a pairing request.

**Comment by maxileith** [comment]
@Glec6 fixed in v0.3.1-beta.1

**Comment by johnlietzke** [comment]
On a Pi 4 running Raspberry Pi OS and cannot find the `~/.pyatv.conf`.  Have one ATV paired 3 not promoting for the pin and one throwing an error. 

Any idea where ~/.pyatv.conf is located?

**Comment by maxileith** [comment]
Hi @johnlietzke ,

if the issue is still present, please open a bug report.
