### ISSUE TITLE
AvadaKedavra in Automations

### ISSUE THREAD

**Issue by Crousinon** [maxileith/homebridge-appletv-enhanced#127]
### Current Situation

You can activate AvadaKedavra manually with the home app

### Proposed Change

I want to use this feature in automations like a switch. Is this possible?

**Comment by Crousinon** [comment]
My bad. It is already possible.

**Comment by maxileith** [comment]
For somebody that is looking for a solution and coming across this issue, you can change the input to avada kedavra in an automation.
