### ISSUE TITLE
'MacOS 19.6.0' is not supported by the plugin Homebridge Apple TV Enhanced. 

### ISSUE THREAD

**Issue by mrmaximas** [maxileith/homebridge-appletv-enhanced#133]
### Current Situation

When plugin/childbridge starts on Mac OS Catalina latest i have this WARNING

### Logs

```Markdown
'MacOS 19.6.0' is not supported by the plugin Homebridge Apple TV Enhanced. You will likely experience problems. However, you may get the plugin to work on your system.
```

### Configuration

```JSON
{
            "mediaTypes": [],
            "deviceStates": [],
            "remoteKeysAsSwitch": [
                "turn_off",
                "turn_on"
            ],
            "customInputURIs": [],
            "discover": {
                "unicast": [
                    "192.168.xx.xx",
                    "192.168.xx.xx"
                ],
                "blacklist": [],
                "multicast": false
            },
            "name": "Apple TV Enhanced",
            "avadaKedavraAppAmount": 15,
            "disableVolumeControlRemote": false,
            "forceVenvRecreate": false,
            "logLevel": 4,
            "_bridge": {
                "username": "0E:34:62:xx:xx:xx",
                "port": 39061
            },
            "platform": "AppleTVEnhanced"
        }
```

### Environment

- OS: Mac OS Catalina 10.15.7
- Homebridge: 1.7.0
- Apple TV Enhanced: v0.7.1-1
- Node: v20.10.0 
- npm: 10.2.3
- Python: 3.9.4

**Comment by maxileith** [comment]
This is expected. Like the Warning says, I do not officially support MacOS. Though, it might run alright since Unix is similar to Linux.

**Comment by mrmaximas** [comment]
> This is expected. Like the Warning says, I do not officially support MacOS. Though, it might run alright since Unix is similar to Linux.
> 
> Generally speaking, I wouldn't recommend to host any server application on a Mac.

I see your point. My question is about the displayed os version from future ;)
BTW homebridge has been working on my 12 y.o. mac mini for 3 years, but not only hb. node-red, mosquitto, z2m, influxdb, grafana - all works fine. 
thanks for you hard work!

**Comment by maxileith** [comment]
This is what node is returning. It's probably the kernel version, though I am not a Mac expert or have used a Mac ever 😉. Would be nice if you could confirm if this is the kernel version.

https://github.com/maxileith/homebridge-appletv-enhanced/blob/f132856df54ee2db3a76a709b78454b89eb5b474/src/checkOS.ts#L13

**Comment by mrmaximas** [comment]
> This is what node is returning. It's probably the kernel version, though I am not a Mac expert nor have I ever used a Mac 😉. Would be nice if you could confirm if this is the kernel version.
> 
> https://github.com/maxileith/homebridge-appletv-enhanced/blob/f132856df54ee2db3a76a709b78454b89eb5b474/src/checkOS.ts#L13

y're rignt :-)
 uname -a
Darwin NVR.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 x86_64

**Comment by mrmaximas** [comment]
@maxileith sorry to ask here. how about a fix release  with a mac address issue? https://github.com/maxileith/homebridge-appletv-enhanced/issues/20

**Comment by mrmaximas** [comment]
> As described in #20 I currently wait for the next release of pyatv, which will include [postlund/pyatv#2282](https://github.com/postlund/pyatv/pull/2282).

in your experience, how long can it take?

**Comment by mrmaximas** [comment]
Is there no other way to add the MAC addresses of apple tvs that I know?

**Comment by maxileith** [comment]
> in your experience, how long can it take?

I have written everything I know so far in issue #20. Everything else would be speculation. However, it is very likely that this issue will be fixed until the end of the year.

These projects are maintained by passionate people in their free time. Sometimes the private life just does not allow to review a PR on the same day. It may take it's time. So never stress any FOSS developer nor stress anybody else in their freetime.

Other people are waiting since November 6th for a fix of this issue.
