### ISSUE TITLE
Configurable Delay for deviceStates 

### ISSUE THREAD

**Issue by failbit** [maxileith/homebridge-appletv-enhanced#136]
### Current Situation

State changes for example from _Playing_ to _Paused_ are immediately sent to the motion sensors. This is in most cases exactly what you want and therefore it should stay the default.

### Proposed Change

It would be nice to have a configurable delay for those state-changes (in seconds). Usecase is this: I have an automation configured, which brightens the light if the deviceState is _Paused_. The lights get dimmed when the deviceState is _Playing_. This automation works great except that even when an episode of an series ends and should continue with the next episode, its a short change in deviceState which leads to dimming and brightening the lights (which is not desired). 

A Change  in the deviceState should lead to wait (configured delay)  and check if there still is a change in the deviceState and only then set the motion sensor. 

If this is too corner-case, I could work around this with a ShortCut-Automation. Which is always a pain.

**Comment by maxileith** [comment]
I have a similar use case. In the following, the automation will only continue if Play is on for 3 seconds.

However, adding a configuration option might be a good idea.

![image](https://github.com/maxileith/homebridge-appletv-enhanced/assets/44269066/ecec9e04-681f-4527-9082-960fded79c97)

**Comment by maxileith** [comment]
I have added the feature. Could you please test it with version v0.8.0-0 and give me some feedback. You can configure it using the config ui.
