### ISSUE TITLE
Update URI Short Name After Adding Device

### ISSUE THREAD

**Issue by ukiews** [maxileith/homebridge-appletv-enhanced#142]
Is it possible to update the short name of a URI after the device has already been added to the Home app?

**Comment by maxileith** [comment]
You can simply change the name in the Home app.

**Comment by ukiews** [comment]
> You can simply change the name in the Home app.

Change the URI input name? How would one do that? It only offers to change input names upon first adding the ATV.

**Comment by maxileith** [comment]
You can do that in the device settings of the Apple TV device. In this screenshot, Rogue One is an URI.

![image](https://github.com/maxileith/homebridge-appletv-enhanced/assets/44269066/0aa0d106-7dda-417e-a9fa-46965738ba6c)

**Comment by ukiews** [comment]
Strange, I do not see this option on my iPhone. After the Status section in only shows device details like Manufacturer etc.. But on the Mac app the inputs do appear... Thanks.

**Comment by maxileith** [comment]
You need to navigate to the actual device first, so do not look at the group of devices ...

![image](https://github.com/maxileith/homebridge-appletv-enhanced/assets/44269066/158cd9f9-7d02-4c97-8ccc-9b0bbdb440b1)

![image](https://github.com/maxileith/homebridge-appletv-enhanced/assets/44269066/37dd0e89-6974-4935-8fb9-007b0992ccde)

Then there should be the inputs ...
