### ISSUE TITLE
Apple TV with HomePod as default speaker doesn't update if use physical remote

### ISSUE THREAD

**Issue by Glec6** [maxileith/homebridge-appletv-enhanced#15]
So works great with all apple TV's that don't have default speakers set as HomePod or HomePod mini. If my Apple TV 4K has its default speakers set to HomePod mini then in HomeKit/homebridge the device doesn't update. I still can control the device from HomeKit,it just wont update if controlled by the physical remote. Any thoughts on why this is the case?

**Comment by ahwman** [comment]
I also have one Apple TV tied to a HomePod stereo pair as default speakers and noticed that each time I restart Homebridge, the prior device state is not remembered. This results in the Apple TV always turning on after restarting Homebridge, regardless of the prior device state.

**Comment by maxileith** [comment]
This is a known bug to pyatv which there is currently no workaround. See here: https://pyatv.dev/support/faq/#power-state-is-not-updated-when-using-external-speaker-eg-homepod

**Comment by maxileith** [comment]
However, this should be added to the README.
