### ISSUE TITLE
Backup/Restore failures with AppleTV-enhanced

### ISSUE THREAD

**Issue by PaTall** [maxileith/homebridge-appletv-enhanced#160]
### Current Situation

Hi Max,   thanks for your plug-in.  I have noticed that after installing your plug-in, the HB backup/restore experiences failures.  Some specifics:
1. After installing the plug-in my backup size went up dramatically from <1Mb to over 70MB.
2. this larger file fails to Restore generating an error by HB.
3. I tracked down the large file in the backup tar.gz and it was a folder: appletv-enhanced.
4. Upon uninstalling the plug-in and deleting the folder /var/lib/homebridge/appletv-enhanced  the HB backup/restore functionality now runs successfully.

Is it possible that the plug-in creates files not suitable for the standard HB Backup/Restore function?

### Logs

```Markdown
n/a
```

### Configuration

```JSON
n/a
```

### Environment

- OS:
- Docker:
- Homebridge:
- Apple TV Enhanced: v1.01
- Node:
- npm:
- Python:
- Pip:

**Comment by maxileith** [comment]
This issue has already been fixed in the Homebridge UI, see https://github.com/homebridge/homebridge-config-ui-x/issues/1955. When generating a backup with Config UI 4.54.2 or later, this shouldn't be an issue anymore.
