### ISSUE TITLE
virtualenv module is not installed

### ISSUE THREAD

**Issue by onkben** [maxileith/homebridge-appletv-enhanced#163]
### Current Situation

Apple TV Enhanced is throwing the following error on startup:

### Logs

```console
[Apple TV Enhanced] Python check: virtualenv python module is not installed. You need to install the python package virtualenv either by using 'python3 -m pip install virutalenv' or installing it via system packages. On debian based distributions this is usally 'sudo apt install python3-venv'
```

### Configuration

```JSON
}
            "name": "Apple TV Enhanced",
            "deviceStateDelay": 0,
            "avadaKedavraAppAmount": 15,
            "disableVolumeControlRemote": false,
            "forceVenvRecreate": true,
            "logLevel": 3,
            "platform": "AppleTVEnhanced"
        }
```

### Environment

- OS: Synology 
- Docker: true 
- Homebridge: 1.7.0 
- Apple TV Enhanced:1.0.1 
- Node: v20.10.0
- npm: 10.2.3
- Python: 3.8.10
- pip: 20.0.2

**Comment by maxileith** [comment]
Before we start ... only write in English. This makes sure that everybody can follow the conversation.

**Comment by maxileith** [comment]
Which version of the docker image are you using?

**Comment by onkben** [comment]
It is okay for me

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Maximilian Leith ***@***.***>
Gesendet: Saturday, January 6, 2024 1:52:35 PM
An: maxileith/homebridge-appletv-enhanced ***@***.***>
Cc: Jörg Trieu ***@***.***>; Author ***@***.***>
Betreff: Re: [maxileith/homebridge-appletv-enhanced] virtualenv module is not installed (Issue #163)


Before we start ... only write in English. This makes sure that everybody can follow the conversation.

**Comment by onkben** [comment]
> Which version of the docker image are you using?
sorry where can i find this, i see that it is the last one from onzu

**Comment by maxileith** [comment]
Just because it is tagged as `latest` doesn't mean that it is the latest.

I am not here to explain you the basics of docker.

I am not familiar with Synology.

You are probably not fulfilling the requirements that you should have read before installing the plugin. from the README:

> * Python virtual environment module virtualenv. (the plugin will create a virtual environment on startup and will install python dependencies in this virtual environment)
>   * On homebridge apt-package >=1.1.4 the python module is installed automatically as a dependency, see homebridge/homebridge-apt-pkg#16
>     * raspian image >= 1.1.2 includes this apt-package, so there is no need to install it manually.
>     * homebridge-docker >= 2023-11-28 includes this apt-package, so there is no need to install it manually.
>   * Otherwise, the python module virtualenv has to be installed manually. This won't be handled by the plugin itself.
>     * On debian-based distros: sudo apt install python3-venv
>     * Installation on other distros may vary

**Comment by onkben** [comment]
ok thanks I check this

**Comment by maxileith** [comment]
Especially **homebridge-docker >= 2023-11-28**

**Comment by maxileith** [comment]
Alternatively, you can just execute `sudo apt install python3-venv` in the console as suggested by the error message in the log.

**Comment by onkben** [comment]
this error then occurs  Package 'python3-venv' has no installation candidate

**Comment by maxileith** [comment]
Then you are using a very old docker image which does not even use Ubuntu 22.04 as its base image. You really should keep your software uptodate. You can use ˋpython3 -m pip install venvˋ to install the required module.

However, this is not the docker way since this will be discarded when updating the image because docker containers are stateless. Just update your image to the latest one https://hub.docker.com/layers/homebridge/homebridge/latest/images/sha256-392a3913060b4d3a12fd19845074ac6dee032948763306f3bba1795ac6248bae

**Comment by onkben** [comment]
Unfortunately it does not work either, this message appears.
# python3 -m pip install venv      
                                                                                         
ERROR: Could not find a version that satisfies the requirement venv (from versions: none)                                 
ERROR: No matching distribution found for venv

**Comment by maxileith** [comment]
It is `virtualenv` not `venv`. And as I said, it is the cleaner way to just update the image.

**Comment by maxileith** [comment]
@onkben any updates?

**Comment by onkben** [comment]
Thanks for the request I will update the docker the days

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Maximilian Leith ***@***.***>
Gesendet: Sunday, January 7, 2024 5:12:01 PM
An: maxileith/homebridge-appletv-enhanced ***@***.***>
Cc: Jörg Trieu ***@***.***>; Mention ***@***.***>
Betreff: Re: [maxileith/homebridge-appletv-enhanced] virtualenv module is not installed (Issue #163)


@onkben<https://github.com/onkben> any updates?
