### ISSUE TITLE
Set as TV Box or Apple TV

### ISSUE THREAD

**Issue by imtitanic** [maxileith/homebridge-appletv-enhanced#191]
### Current Situation

For now I only can set the Apple TV as himself, an Apple TV, but the icon of the device looks weird to me also is “duplicated” with the original device

### Proposed Change

There is a way to select in the config of the plugin if I want to show that as TV Box, Stick or an Apple TV? For example.

**Comment by maxileith** [comment]
Hi @imtitanic. I have added the feature. Could you install version v1.2.0-5 and give me some feedback?

![image](https://github.com/maxileith/homebridge-appletv-enhanced/assets/44269066/c2be9b66-0987-42f6-8025-a1407f4fea29)

**Comment by imtitanic** [comment]
> Hi @imtitanic. I have added the feature. Could you install version v1.2.0-5 and give me some feedback? You need to repair the homebridge accessory with your Home app in order to see the changes. This is a HomeKit limitation.
> 
> ![image](https://private-user-images.githubusercontent.com/44269066/298125492-c2be9b66-0987-42f6-8025-a1407f4fea29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3Nzk1NDcsIm5iZiI6MTcwNTc3OTI0NywicGF0aCI6Ii80NDI2OTA2Ni8yOTgxMjU0OTItYzJiZTliNjYtMDk4Ny00MmY2LTgwMjUtYTE0MDdmNGZlYTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE5MzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMDIwYmQxMWNkMjEyNDQ5YTczNjEyZDRjNjFhNGI5ZDdjZTc0OGUxZGRmMDYxMmE2NzBjNDA4ZmY2YzJmNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XoGDtVa-8LkbkGbxJQqnL3wwk-4CRP7MtXtuZxUAu2U)

Hi, I use that version and everthing works fine for the moment, my Apple TV show as box correctly
