### ISSUE TITLE
Any plan to migrate to Windows system?

### ISSUE THREAD

**Issue by BrianZ96** [maxileith/homebridge-appletv-enhanced#193]
### Current Situation

Is there any future plan to add functionality that can run on Windows?

### Proposed Change

For me my entire homebridge runs on my spare Windows laptop. So it would be great if a Window system is supported.

**Comment by BrianZ96** [comment]
If I have a rasp pi board, can this plugin run there?

**Comment by maxileith** [comment]
The plugin runs on any Linux system, including a Raspberry Pi.

There are no plans to support Windows.
