### ISSUE TITLE
Consider having an option for the top level device NOT to be a TV/Set top box

### ISSUE THREAD

**Issue by KE55ARD** [maxileith/homebridge-appletv-enhanced#210]
### Current Situation

Once you have paired an Apple TV, you add it into the home app with a pairing code, and all the desired devices appear under the top level bridge device which is classified as a "set top box".

### Proposed Change

I propose that you add an option to make the top level device a more generic bridge of some kind instead.

### Additional Context

The reason for this is that Apple (inexplicably) hide TVs and Speakers from third party apps. Which means we lose out on a massive amount of utility from this plugin. As I cannot do the thing which I would likely use most, check the "playing" motion sensor in a condition on various automations. The only way I can do this currently is convert the automation to a Shortcut and add an IF statement to check the playing sensor. But I hate using Shortcut automations unless I absolutely have to because they are so damn slow.

**Comment by KE55ARD** [comment]
Hmmm why do I have a feeling I've JUST found this option 🤦‍♂️

Although it says I'll need to re-add the device for it to take effect, aaannnddd it's not finding it now...

**Comment by maxileith** [comment]
See #209

**Comment by KE55ARD** [comment]
Ok in addition to this, I found the option to make the TVs appear as "set top boxes". I selected it, saved and went to re-add all of my ATVs and now the most important one doesn't show up as available to add into my Apple Home again (typical!). Although I can see in the logs that the plugin has maintained a connection to it and see events, I just cannot re-add it to my home. I've gone so far as to uninstall and re-install the plugin and I cannot add it again 😔

**Comment by maxileith** [comment]
Take a look at #209 and let me know wether or not it worked for you :)

**Comment by KE55ARD** [comment]
Ahhhh I didn't know that was a thing 🤦‍♂️ thanks!

I'll try that now, but my original question stands I think. As I don't think a set top box behaves any differently to third party apps?

**Comment by maxileith** [comment]
@KE55ARD yep, I did not overlook that. However, I am currently traveling and can't take a deeper look into that. Maybe at the end of next week.

**Comment by KE55ARD** [comment]
No worries, just thought I'd reiterate. Hopefully my suggestion makes some sense. Let me know if you need any more from me.

And most importantly enjoy your travels :)

**Comment by KE55ARD** [comment]
Been thinking about this a little of the weekend, and it may make sense for the primary functionality (on/off, channel selection) to stay within a TV type device.But the option I’m suggesting would then segment all the motion sensors and switches into a second bridge (which I guess you’d annoyingly have to pair separately) so they could be seen and used by third party apps.James KennardOn 28 Jan 2024, at 12:03, Maximilian Leith ***@***.***> wrote:﻿
@KE55ARD yep, I did not overlook that. However, I am currently traveling and can't take a deeper look into that. Maybe at the end of next week.

**Comment by maxileith** [comment]
Please do not reply via E-Mail. That just makes a big mess that I have to clean up manually in the issue.

**Comment by maxileith** [comment]
After some investigation it becomes clear that the architecture of the plugin would need to be changed significantly. I don't think it is worth the effort. I currently have no usecase myself. However, feel free to open a PR.
