### ISSUE TITLE
New input added to each of my Apple TV’s “Avada Kedavra”

### ISSUE THREAD

**Issue by ahwman** [maxileith/homebridge-appletv-enhanced#22]
Not a big deal, but oddly I noticed a new input added to each of my Apple TV’s labeled “Avada Kedavra”.  I simply unchecked it but wanted to report it nonetheless…

**Comment by maxileith** [comment]
Yeah, this is actually a feature, like written in the README. When you select this input it will close all opened apps on your Apple TV :).

If you do not want that, just uncheck the input as you have already written.

**Comment by ahwman** [comment]
This is amazing!  One question, after using this the settings app is loaded when turning on Apple TV.  Is there any way to avoid this?On Nov 8, 2023, at 12:10 PM, Maximilian ***@***.***> wrote:﻿
Yeah, this is actually a feature, like written in the README. When you select this input it will close all opened apps on your Apple TV :).
If you do not want that, just uncheck the input as you have already written.

**Comment by maxileith** [comment]
@ahwman I could not reproduce what you have described:

1. Executr Avada Kedavra
2. Turn off Apple TV
3. Turn on Apple TV

Result: Home Screen

So on my setup, the settings app does not open after a restart.

**Comment by ahwman** [comment]
I wonder if this has something to with the issue related to HomePods as I can’t duplicate this behavior on any of my other Apple TV’s which are not using HomePods as the default speaker.  Even if I disable this input, every time I tap on the Apple TV plugin, it immediately launches the settings app and displays it in the input of the icon…On Nov 8, 2023, at 5:22 PM, Maximilian ***@***.***> wrote:﻿
@ahwman I could not reproduce what you have described:

Executr Avada Kedavra
Turn off Apple TV
Turn on Apple TV

Result: Home Screen
So on my setup, the settings app does not open after a restart.

**Comment by ahwman** [comment]
﻿Disregard 😀.  I had a wonky automation that was causing the settings app to load..  So sorry…On Nov 8, 2023, at 5:22 PM, Maximilian ***@***.***> wrote:﻿
@ahwman I could not reproduce what you have described:

Executr Avada Kedavra
Turn off Apple TV
Turn on Apple TV

Result: Home Screen
So on my setup, the settings app does not open after a restart.
