### ISSUE TITLE
Adding a motion sensor for power state?

### ISSUE THREAD

**Issue by Lee181** [maxileith/homebridge-appletv-enhanced#225]
### Current Situation

There are motion sensors for playing, paused, idle etc. and I can work with them to do some internal automations (via HomeKit) and also external automations (via Homebridge->FHEM).

The only thing I am missing for now is an additional sensor for the general Apple TV power state, as for now I can see the homekit sensors only in FHEM, not the whole Apple TV device.

### Proposed Change

What do you think about adding an optional sensor for the power state which is set to "movement", when the Apple TV is started up?
And could you work it out, that when shutting down Apple TV, it gets set to "no movement"?

For now I can see, all the other sensors (I use playing and the media types) do not get reset when Apple TV gets powered down. They just stay in the last state even if the Apple TV is switched off. Is this a bug or a feature?

### Additional Context

Thank you very much for this great plugin! I closed the gap between my FHEM and Apple TV, so I could move my home theater from Kodi/Raspberry to Apple TV.
I apreciate your work!

**Comment by maxileith** [comment]
> For now I can see, all the other sensors (I use playing and the media types) do not get reset when Apple TV gets powered down. They just stay in the last state even if the Apple TV is switched off. Is this a bug or a feature?

Can you check v1.2.1 and let me know if the issue is resolved on your side?

> The only thing I am missing for now is an additional sensor for the general Apple TV power state

This won't be added since this value can be obtained from the Apple TV device. However, #210 could resolve this problem.

**Comment by Lee181** [comment]
> Can you check v1.2.1 and let me know if the issue is resolved on your side?

I've installed v1.2.1 and the motion sensors behave now as expected: When turnig off Apple TV, they get reset correctly. Thank you for the quick fix!

> This won't be added since this value can be obtained from the Apple TV device. However, #210 could resolve your FHEM problem.

Okay, perhaps you could think over it again? (Vielleicht wenn ich ganz lieb bittebitte sage? 🥺 )

As far as I understand, #210 is a different problem... 
My problem is: I do all the automation of my home in FHEM. The plugin for FHEM which I found today in the FHEM-Forums [topic](https://forum.fhem.de/index.php?topic=119483.0;all)  seems very rudimentary/testing, but it works! And as the author describes, it can only see and control HomeBridge (NOT native HomeKit!) devices, furthermore only basic things like switches, bulbs, sensors and so on. I don't see the Apple TV there neither the Homekit-device nor the Homebridge-device created by your plugin in FHEM. And as the project seems to be abandoned since 2022, I have not so much hope that he will add a complex device like the Apple TV, but I will try and ask also there.

I was just wondering, if any one else besides me would benefit of adding the power state as an optional motion sensor.
For my (simple) automations the power state an play/pause/idle are absolutely enough (I don't need full control over the Apple TV device like in Homekit). And I was hoping that it should be not that much work to add the power state sensor...

For now I have added some virtual devices in FHEM which are triggered by the sensors via Homekit-automations and after all can be seen from FHEM. But I don't know how reliable  that will work in future... 
My tests with the play/pause motion sensors I can see directly (thanks to the new FHEM-plugin) since today work very well, just the power state is missing...
I was also thinking about taking the presence of any of the motion sensors like play, pause, idle, Video as a kind of a heartbeat to consider the Apple TV as powered on. But I don't know how reliable this would work in FHEM.

Perhaps you have some time left one day for the (optional) power state sensor? ;) And of course if you see the benefit for other users...

**Comment by maxileith** [comment]
> Perhaps you have some time left one day for the (optional) power state sensor? ;) And of course if you see the benefit for other users...

I don't think that this will benefit a large number of users. Your usage with FHEM (that most people probably don't even know) is an edge case. Furthermore, the question should not be whether I have the time to implement that but rather if the power state information should be published redundantly.
