### ISSUE TITLE
Removed from home app now can't readd

### ISSUE THREAD

**Issue by Glennkh** [maxileith/homebridge-appletv-enhanced#228]
### Current Situation

I removed the Apple TV from the home app and now I can't readd it.

I tried the following I am able to repair the apple tv to the plugin but the Apple TV never becomes discoverable in the home app again for me.

https://github.com/maxileith/homebridge-appletv-enhanced/issues/12
https://github.com/postlund/pyatv/issues/2277

I tried adding a separate Apple TV that was never paired to my home app before and that one was discoverable and successfully added to the home app. 

### Logs

```console
...
```

### Configuration

```JSON
{
            "name": "Apple TV Enhanced",
            "deviceStates": [
                "paused",
                "playing"
            ],
            "deviceStateDelay": 0,
            "avadaKedavraAppAmount": 15,
            "disableVolumeControlRemote": false,
            "setTopBox": false,
            "discover": {
                "multicast": true
            },
            "forceVenvRecreate": false,
            "logLevel": 5,
            "deviceSpecificOverrides": [
                {
                    "overrideMediaTypes": false,
                    "overrideDeviceStates": false,
                    "overrideDeviceStateDelay": false,
                    "deviceStateDelay": 0,
                    "overrideRemoteKeysAsSwitch": false,
                    "overrideAvadaKedavraAppAmount": false,
                    "avadaKedavraAppAmount": 15,
                    "overrideCustomInputURIs": false,
                    "overrideDisableVolumeControlRemote": false,
                    "disableVolumeControlRemote": false,
                    "overrideSetTopBox": false,
                    "setTopBox": false
                }
            ],
            "platform": "AppleTVEnhanced"
        }
```

### Environment

- OS: 
- Docker: 
  - Image Version: 
- Homebridge: 
- Homebridge Config UI: 
- Storage Path: 
- Apple TV Enhanced: 
- Node: 
- npm: 
- Python: 
- pip: 
- HDMI hops: 
- HomePod as default speaker:

**Comment by maxileith** [comment]
#209

**Comment by Glennkh** [comment]
Nice! that worked for me. Thanks
