### ISSUE TITLE
"Hey Siri, turn Apple TV on" does not turn Apple TV Enhanced on

### ISSUE THREAD

**Issue by astrogab42** [maxileith/homebridge-appletv-enhanced#246]
### Current Situation

Hey! I have a HomePod (2nd gen) connected wirelessly to my Apple TV. When I use Siri (both the HomePod and my iPhone), the Apple TV turns on, but the Apple TV Enhanced accessory does not turn on. Basically, it is like they are not "synchronized". 

It is the same if I use the power button on the iPhone Apple TV Remote app

Is this a know issue? Do you have any solution for that? I search on GitHub and [Reddit](https://www.reddit.com/r/homebridge/comments/17mquj7/apple_tv_enhanced_plugin/) but I did not find any suggestion (I hope this is not a silly question...)

Thanks!!

### Logs

```console
/
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "deviceStateDelay": 0,
    "remoteKeysAsSwitch": [
        "select",
        "turn_off",
        "turn_on"
    ],
    "avadaKedavraAppAmount": 5,
    "disableVolumeControlRemote": true,
    "setTopBox": false,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "platform": "AppleTVEnhanced"
}
```

### Environment

- OS: Linux Debian on pc server
- Docker: false
- Homebridge: 1.7.0
- Homebridge Config UI: 4.55.1 
- Storage Path: /var/lib/homebridge/
- Apple TV Enhanced: 1.2.3
- Node: 12.22.12
- npm: 7.5.2
- Python: 3.9.2
- pip: 20.3.4
- HDMI hops: false
- HomePod as default speaker: true

**Comment by maxileith** [comment]
This has been discussed many times, e.g. #15, #155, #164.

Additionally, there is a section in the README regarding your topic.

> If using audio output devices other than the Apple TV itself, the Apple TV is always reported as powered on. This is a known issue of the dependency pyatv, see postlund/pyatv#1667. As a result, the Apple TV device will only be shown as off in HomeKit when powered off via the Apple TV device in HomeKit. After restarting the plugin the device will always be shown as on.

Next time you have an issue read the README and take a proper look into the existing issues.

**Comment by maxileith** [comment]
Besides that ... you should really update your Node ^^
