### ISSUE TITLE
Error wen adding device : no /homebridge/node_modules/homebridge-appletv-enhanced/dist/html folder

### ISSUE THREAD

**Issue by FlorianFSA** [maxileith/homebridge-appletv-enhanced#25]
Hello ! 

I'm trying to use the plugin on a docker container of homebridge (latest homebridge:homebridge image).
The plugin installation _seems_ to be successful, but I'm stuck with the following error when the plugin tries to add a discovered device.

`Error: ENOENT: no such file or directory, open '/homebridge/node_modules/homebridge-appletv-enhanced/dist/html/input.html'`

I checked the content of `/homebridge/node_modules/homebridge-appletv-enhanced/dist/` and indeed the whole _html_ folder is absent.

**Comment by maxileith** [comment]
Hi @FlorianFSA ,

thank for letting me know. I changed something in the package.jdon and the html files were no longer present in the package. Please try again with v0.3.4-beta.2

**Comment by FlorianFSA** [comment]
Just tried with the new fixed version and everything works flawlessly ! 

Thank you for what you do for the community :)
