### ISSUE TITLE
Disable remote support

### ISSUE THREAD

**Issue by drewspmartin** [maxileith/homebridge-appletv-enhanced#253]
### Current Situation

Hello, I use the plugin to determine playing or not which allows me to make a play/pause toggle. That's all I need it for, but unfortunately when I got to iOS remotes, I have double remotes. The real iOS remote and the plugin remote. Is there a way that I can disable the remote from the plugin?

### Proposed Change

Disable iOS remote option

**Comment by maxileith** [comment]
This is a HomeKit limitation. Television devices always expose a remote.

**Comment by NewtonSnoopin** [comment]
It's not possible to create the motion sensors for playing, paused, movie and tv like it already does?

**Comment by drewspmartin** [comment]
So I have a Flic button I am trying to program to be:

One press: Toggle Pause/Play
Two press: Toggle Mute/Unmute

I cant do the mute toggle as you know, but I can do the pause toggle as a shortcut to see if TV is playing or not. If it is, pause, if it isn’t, play.

When I get this all setup, I have two remotes in the iOS remote app. Just seeing if I can remove that.

Are you saying the motion sensors for playing can be used without pairing the remote thus not having the second iOS remote?

Also, I am in Wuppertal for work, think I am near you.

Have a happy rainy day.


From: NewtonSnoopin ***@***.***>
Date: Wednesday, February 21, 2024 at 12:51 AM
To: maxileith/homebridge-appletv-enhanced ***@***.***>
Cc: drewspmartin ***@***.***>, Author ***@***.***>
Subject: Re: [maxileith/homebridge-appletv-enhanced] Disable remote support (Issue #253)

It's not possible to create the motion sensors for playing, paused, movie and tv like it already does?

**Comment by maxileith** [comment]
> When I get this all setup, I have two remotes in the iOS remote app. Just seeing if I can remove that.

As I have already written, this is not possible.

> It's not possible to create the motion sensors for playing, paused, movie and tv like it already does?

I am assuming you mean to only expose the motion sensors without the Apple TV (you need to be more specific, not very erlegant to be forced to make assumption to answer you). Technically, this is possible. However, this would require a rather big change of the archtiecture of the plugin so I do not plan to implement this.

**Comment by drewspmartin** [comment]
I was responding to NewtonSnoopin, I have already accepted this will not be resolved as you closed the ticket.
