### ISSUE TITLE
Option to hide remote entirely

### ISSUE THREAD

**Issue by NewtonSnoopin** [maxileith/homebridge-appletv-enhanced#254]
### Current Situation

Hello I have my AppleTV's added via the normal HomeKit way and also through this plugin. 

My problem is its duplicating the remotes inside the remote app when I only want the motion detection for playing, pause, music and tv. 

### Proposed Change

Can you please add an option to remove the remote entirely and just add the sensors.

**Comment by maxileith** [comment]
This already been discussed multiple times. Please search through the existing issues before opening a new one. The last time this has been mentioned was less than 24 hours ago. See #253
