### ISSUE TITLE
Issues using Blacklist to exempt devices and Credentials do not appear to stay valid

### ISSUE THREAD

**Issue by jtwurth** [maxileith/homebridge-appletv-enhanced#255]
### Analysis

Blacklist fails to prevent some devices from pairing with the plugin. Then multiple units do not maintain credentials and repeated throw up PIN numbers on the screens.

### Expected Behavior

I expected that any blacklisted AppleTVs would not continually attempt to pair with the plugin and throw PIN code up on the screen.

My other expectation was that once configured I could use the triggers exposed by your plugin to run HomeKit automations based on their conditions.

### Steps To Reproduce

1 - After installing plugin and setting up the Child Bridge it starts discovering my four Apple TVs. In this instance I immediately started blacklisting (using the MACs in the plugin log) three of my devices that I planned to configure later. I wanted to focus only on the Living Room AppleTV. 

2 - I restarted the bridge and the logs indicate that it was no longer attempting to connect to those blacklisted devices.

3 - I followed the steps to add my AppleTV as a bridge using the code from the log. This was successful but immediately after the logs indicate that my Bedroom AppleTV was trying to pair. (I confirmed the MAC was correct and still saved) 

4 - Then the device I had been configuring started getting prompted to enter a PIN again while I was watching TV. The log shows that my Living Room Apple TV's credentials were longer valid. I tried entering one of the PINs but it just continued to ask for another PIN. This behavior starts at 12:40:54 in the attached log 

5 - At this point I disabled the plugin

**on a previous attempt it was a my Kitchen AppleTV that was trying to connect even though it had been blacklisted. So it appears to not be consistent. These are all AppleTV 4K except for the Bedroom which is an AppleTV HD

### Logs

```console
See the attached log in 'Additional Context'
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "deviceStates": [
        "playing"
    ],
    "deviceStateDelay": 0,
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "setTopBox": false,
    "discover": {
        "multicast": true,
        "blacklist": [
            "C8:D0:83:C0:73:31",
            "F0:B3:EC:5B:BC:A7",
            "C8:69:CD:09:EE:50"
        ]
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "_bridge": {
        "username": "0E:E7:FE:AF:7D:D8",
        "port": 39105
    },
    "platform": "AppleTVEnhanced"
}
```

### Environment

- OS: Raspberry Pi OS Bullseye 11
- Docker: false
  - Image Version: 
- Homebridge: 1.7.0
- Homebridge Config UI: 4.55.1
- Storage Path: /var/lib/homebridge
- Apple TV Enhanced: 1.2.3
- Node: 20.11.1
- npm: 0.39.7
- Python: 3.9.2
- pip: 20.3.4
- HDMI hops: 0. All AppleTVs are connected directly to TV's HDMI input
- HomePod as default speaker: True on two out of four of the devices.

### Additional Context

[homebridge-appletv-enhanced.log.txt](https://github.com/maxileith/homebridge-appletv-enhanced/files/14320153/homebridge-appletv-enhanced.log.txt)

**Comment by maxileith** [comment]
It would be helpful if you could post the following log message, without hiding the MAC-Adress.

```logs
[2/17/2024, 12:40:54 PM] [Apple TV Enhanced] [I] Platform: Adding Apple TV Bedroom AppleTV (hidden MAC)
```

**Comment by jtwurth** [comment]
Gotcha. Sorry about that. See attached.

[homebridge-appletv-enhanced.log-2.txt](https://github.com/maxileith/homebridge-appletv-enhanced/files/14320532/homebridge-appletv-enhanced.log-2.txt)

**Comment by maxileith** [comment]
Could you please install v1.2.4-1 and test if the version is working for you?

**Comment by jtwurth** [comment]
I've upgraded to your beta version and so far so good. I was able to add two of my devices. The blacklist appears to be holding and credentials staying valid. It has been running for about 12 hours without an issue. I've also generated some automations based on your plugin and they worked perfectly.

Thank you! This was such a great idea for a plugin.
