### ISSUE TITLE
Phyton-virtualen doesn‘t work

### ISSUE THREAD

**Issue by Kohle81** [maxileith/homebridge-appletv-enhanced#265]
### Analysis

I have installed this plugin about config-ui.

### Expected Behavior

After getting log I installed python manual with 
sudo apt-get install python-virtualenv

### Steps To Reproduce

..

### Logs

```console
20/02/2024, 20:02:01] [Apple TV Enhanced] [E] Python check: virtualenv python module is not installed. If you have installed homebridge via the apt package manager, update the homebridge apt package to 1.1.4 or above (this applies for installations based on the Raspberry Pi OS iamge as well). When using the official docker image, update the image to version 2023-11-28 or above. Otherwise install the python virtualenv module manually.
```

### Configuration

```JSON
{
            "name": "Apple TV Enhanced",
            "mediaTypes": [
                "music",
                "tv",
                "video"
            ],
            "deviceStates": [
                "playing"
            ],
            "deviceStateDelay": 0,
            "remoteKeysAsSwitch": [
                "turn_off",
                "turn_on"
            ],
            "avadaKedavraAppAmount": 15,
            "disableVolumeControlRemote": false,
            "setTopBox": false,
            "discover": {
                "multicast": true
            },
            "forceVenvRecreate": false,
            "logLevel": 3,
            "deviceSpecificOverrides": [
                {
                    "overrideMediaTypes": false,
                    "overrideDeviceStates": false,
                    "overrideDeviceStateDelay": false,
                    "deviceStateDelay": 0,
                    "overrideRemoteKeysAsSwitch": false,
                    "overrideAvadaKedavraAppAmount": false,
                    "avadaKedavraAppAmount": 15,
                    "overrideCustomInputURIs": false,
                    "overrideDisableVolumeControlRemote": false,
                    "disableVolumeControlRemote": false,
                    "overrideSetTopBox": false,
                    "setTopBox": false
                }
            ],
            "platform": "AppleTVEnhanced",
            "_bridge": {
                "username": "0E:CA:A4:36:FB:85",
                "port": 54444
            }
```

### Environment

- OS: 
- Docker: 
  - Image Version: 
- Homebridge: 
- Homebridge Config UI: 
- Storage Path: 
- Apple TV Enhanced: 
- Node: 
- npm: 
- Python: 
- pip: 
- HDMI hops: 
- HomePod as default speaker:

**Comment by maxileith** [comment]
1. You said that you got the error that the python virtualenv package is missing and then installed it. Great. What do you want me too answer now?
2. I ask for the environment in the bug template for a reason. Please provide the details I have asked for.

Generally speaking, install the latest homebridge apt-package and use the systems default python installation. If you do so, all dependencies should be there ...

**Comment by Kohle81** [comment]
Sorry for missing the details for my environment:

Raspi 4
OS Raspbian GNU/Linux Bullseye (11)
node 20.10.0
homebridge v. 1.7.0
homebridge-ui 4.55.1

> Am 20.02.2024 um 20:56 schrieb Maximilian Leith ***@***.***>:
> 
> I ask for the environment in the bug template for a reason. Please provide the details I have asked for.

**Comment by Kohle81** [comment]
I have updated with 

sudo apt-get update
sudo apt-get upgrade

Manual installation has not worked by:

pi@homebridge:~ $ sudo apt-get install python-virtualenv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate
