### ISSUE TITLE
Specific apps playing sensor trigger

### ISSUE THREAD

**Issue by denisgabriel5** [maxileith/homebridge-appletv-enhanced#286]
### Preconditions

- [X] The support request template is not a better fit to my question

### Issue

Hi,

Is there possible to condition the playing sensor to work only in some specific apps like Infuse, Netflix, Disney or Amazon Prime?

When I open apps like YouTube or Spotify, the playing sensor triggers and does what I told him to. But in these cases I wouldn't want to run that automation.

**Comment by maxileith** [comment]
#272 might help you

**Comment by maxileith** [comment]
Would be nice if you could let me know whether or not the linked discussion answers your issue. If you need further assistance let me know.

**Comment by denisgabriel5** [comment]
> Would be nice if you could let me know whether or not the linked discussion answers your issue. If you need further assistance let me know.

It worked, thanks a lot.
