### ISSUE TITLE
Add "power" state

### ISSUE THREAD

**Issue by sftsk** [maxileith/homebridge-appletv-enhanced#3]
Hello, thanks for the great plugin!

Are you planning on adding "power" states? Like `sleeping` and `on`?
That would be amazing and the plugin could be used to trigger scenes when the Apple TV is turned on or off.

**Comment by maxileith** [comment]
Hi @sftsk ,

thank you for your festure request. However, it is already possible to trigger an automation based on the power state. In order to achieve that you just need to select "when a device is controlled" or something similar, I dunno since I do not have English as my system language.

![image](https://github.com/maxileith/homebridge-appletv-enhanced/assets/44269066/3894d6c9-f8cf-4bef-b68e-83934c1ef966)

**Comment by sftsk** [comment]
Hello @maxileith,

Thanks for the swift answer.

Your are right but unfortunately Apple has decided not to expose the device status for Apple TVs.
There have been multiple threads over the years (https://www.reddit.com/r/HomeKit/comments/pmx7po/use_appletv_on_as_trigger_for_automation/) and as far as I can tell no good solutions that still work.

**Comment by maxileith** [comment]
Maybe I am overlooking something but from what I can tell from the thread, people are complaining that there is no option to trigger power state related automations based on the vanilla integration of Apple TV in HomeKit.

But exactly that can be achieved by setting the trigger like the following

![image](https://github.com/maxileith/homebridge-appletv-enhanced/assets/44269066/9410fdcf-b744-40d9-8fe7-8a4a5d85d3ca)

If I am still missing something you need to describe your desired automation trigger more clearly.

**Comment by maxileith** [comment]
@sftsk can you confirm that this is what you are looking for?

**Comment by sftsk** [comment]
Hello @maxileith ,

sorry it took me little while to give it another try and debug some related issues. Indeed as you were saying it is possible to use the "enhanced" device as a trigger. I did not notice it at first because the devices had disappeared from the Home app.

It might have been connected with #2. I have now given static IPs to my Apple TVs but the plugin still seems to forget the settings (I don't want any of the additional states and only the main power state). As soon as I reboot Homebridge, all the settings for the plugin are back to default.

I don't know if it's connected but the state of the Apple TV does not always update when it should, therefore the automation is not 100% reliable.

Sorry for mixing up issues within this issue.

**Comment by maxileith** [comment]
Hi @sftsk ,

the IP does not need to be static. #2 is fixed in the latest version.

What do you mean by resets to default? Are only the defaults music, video, playing, paused and stopped there or every possible motion sensor?
