### ISSUE TITLE
Can’t add ATV to Home app

### ISSUE THREAD

**Issue by sethlong1** [maxileith/homebridge-appletv-enhanced#306]
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

I reinstalled the plugin after having installed and configured it then deleted it a few months ago. I manually unpaired the ATV from the plugin using the Settings app on the ATV. It re-paired without issue. I got the HomeKit setup code from the logs and proceeded to add the accessory in the Home app, but it fails repeatedly every time. 

The setup code is the same as for homebridge and other plugins. When I enter it in the Add Accessory window (tap More Options, then tap My accessory isn’t shown here, and then finally tap Enter Code). When I enter the setup code from the logs the Home app goes right back to the Add Accessory screen as if nothing had just happened. The ATV doesn’t get added, no matter how many times I’ve tried. 

### Logs

```console
See attached
```

### Configuration

```JSON
{
            "name": "TuyaWebPlatform",
            "options": {
                "username": "seth@sethlong.com",
                "password": "6wtrNyP8k-XYGHPNp842",
                "countryCode": "1",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        },
        {
            "name": "Apple TV Enhanced",
            "mediaTypes": [
                "music",
                "tv",
                "video"
            ],
            "deviceStates": [
                "paused",
                "playing",
                "stopped"
            ],
            "deviceStateDelay": 0,
            "remoteKeysAsSwitch": [
                "down",
                "home",
                "left",
                "menu",
                "next",
                "play_pause",
                "previous",
                "right",
                "select",
                "stop",
                "turn_off",
                "turn_on",
                "up"
            ],
            "avadaKedavraAppAmount": 15,
            "disableVolumeControlRemote": false,
            "setTopBox": false,
            "discover": {
                "multicast": true
            },
            "forceVenvRecreate": false,
            "logLevel": 3,
            "updateCheckLevel": "stable",
            "deviceSpecificOverrides": [
                {
                    "overrideMediaTypes": false,
                    "overrideDeviceStates": false,
                    "overrideDeviceStateDelay": false,
                    "deviceStateDelay": 0,
                    "overrideRemoteKeysAsSwitch": false,
                    "overrideAvadaKedavraAppAmount": false,
                    "avadaKedavraAppAmount": 15,
                    "overrideCustomInputURIs": false,
                    "overrideDisableVolumeControlRemote": false,
                    "disableVolumeControlRemote": false,
                    "overrideSetTopBox": false,
                    "setTopBox": false
                }
            ],
            "platform": "AppleTVEnhanced",
            "_bridge": {
                "username": "0E:B7:B2:4F:FD:BE",
                "port": 42054
            }
        }
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Raspberry pi OS

### Operating System: Distribution Version

12 (bookworm)

### Docker

no

### Docker Image

None

### Homebridge Version

1.7.0

### Homebridge Config UI Version

v4.55.1

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.2.5

### Node Version

v20.11.1

### NPM Version

10.2.4

### Python Version

3.11.2

### PIP Version

23.0.1

### HDMI Hops

AppleTV -> Samsung q990c -> TV

### Audio Output

no

### Same Subnet

yes

### Additional Context

[homebridge-appletv-enhanced.log.txt](https://github.com/maxileith/homebridge-appletv-enhanced/files/14519393/homebridge-appletv-enhanced.log.txt)

**Comment by maxileith** [comment]
I would try to unpair the Apple TV in homebridge like here: https://github.com/maxileith/homebridge-appletv-enhanced/discussions/209#discussioncomment-8263888

If this does not work out for you, please open an issue in the homebridge repo. The pairing process is handled by homebridge not the plugins.

**Comment by sethlong1** [comment]
That solved it. Thank you!

**Comment by vonPB** [comment]
@sethlong1 Please be more careful when posting your config. You have posted your username and password for your `TuyaWebPlatform` login. Based on your job description from linkedIn I would expect a bit more care :)
