### ISSUE TITLE
Python 3.12.2 instead python 3.11.8

### ISSUE THREAD

**Issue by Afaliwen** [maxileith/homebridge-appletv-enhanced#310]
### Preconditions

- [X] Requirements fulfilled
- [X] The bug is not a known issue
- [X] The bug has not been solved in the past or the solution that was provided in the past does not work on my system
- [X] There is currently no other opened issue that describes this bug
- [X] I cannot find any solution to the problem in GitHub discussions
- [X] I am certain that the problem that I am having is a bug

### Analysis

I use latest home bridge on Mac mini M2 an before the latest update Apple TV Enhanced running well.
I have installed python 3.11 and Python 3.12. After the Update Apple TV Enhanced only finding python 3.12 and don't running and given Error Message: [Apple TV Enhanced] [E] Python check: Python 3.12.2 is installed. However, only Python 3.8 to 3.11 is supported.

### Expected Behavior

configuration of the used python or set en environment variable

### Steps To Reproduce

don't start....

### Logs

```console
[Apple TV Enhanced] [E] Python check: Python 3.12.2 is installed. However, only Python 3.8 to 3.11 is supported.
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "deviceStateDelay": 0,
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "setTopBox": false,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "platform": "AppleTVEnhanced",
    "_bridge": {
        "username": "0E:CF:DE:7B:5A:65",
        "port": 53977
    }
}
```

### Operating System

Mac Os

### Operating System: Bits

64-bit

### Operating System: Distribution

macOS 14.4 23E214 arm64 

### Operating System: Distribution Version

macOS 14.4 23E214 arm64 

### Docker

no

### Docker Image

None

### Homebridge Version

v1.7.1-beta.23

### Homebridge Config UI Version

v4.55.1

### Homebridge Storage Path

/Users/sfi/.homebridge

### Homebridge Apple TV Enhanced Version

v1.2.5

### Node Version

v20.11.1

### NPM Version

10.4.0

### Python Version

3.11.8

### PIP Version

24.0.0

### Audio Output

no

### Same Subnet

yes

**Comment by maxileith** [comment]
Just make sure that the default python version within the environment that homebridge is running in is 3.11.

**Comment by Afaliwen** [comment]
ok, i look for, to fix that. thx.

No, i updated the pluging. In the Version before, the plugin runs well. After install the actual plugin, the message comes up. I read, that you updated dependencies in the last release, and i thougt, thats the bug. 

ok, look to set the python Version in homebridge....
