### ISSUE TITLE
State not syncing when turned off/on with remote ?

### ISSUE THREAD

**Issue by Write** [maxileith/homebridge-appletv-enhanced#321]
### Preconditions

- [X] The support request template is not a better fit to my question

### Issue

Hello thanks for your plugin.

I want to add some automation that act when powering off or powering on the Apple TV. It does works fine when manually clicking the “fake” Apple TV created by this plugin, however when I manually turn on or off the TV with the official Siri remote, the “fake” Apple TV  does not update and thus automations are never run.

Any idea how could I debug this ?

Thanks.

**Comment by maxileith** [comment]
Hi @Write,

does this answer your question? (From the README)

> If using audio output devices other than the Apple TV itself, the Apple TV is always reported as powered on. This is a known issue of the dependency pyatv, see postlund/pyatv#1667. As a result, the Apple TV device will only be shown as off in HomeKit when powered off via the Apple TV device in HomeKit. After restarting the plugin the device will always be shown as on.
