### ISSUE TITLE
TIVIMax is not active in the app list

### ISSUE THREAD

**Issue by onkben** [maxileith/homebridge-appletv-enhanced#346]
### Preconditions

- [X] Requirements fulfilled
- [X] The bug is not a known issue
- [X] The bug has not been solved in the past or the solution that was provided in the past does not work on my system
- [X] There is currently no other opened issue that describes this bug
- [X] I cannot find any solution to the problem in GitHub discussions
- [X] I am certain that the problem that I am having is a bug

### Analysis

TIVIMax is not selected in the app list and switched to active

### Expected Behavior

TIVIMax should be selected when active on the ATV and set to active

### Steps To Reproduce

Start the HomeKit

### Logs

```console
no
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "mediaTypes": [
        "music",
        "tv",
        "unknown",
        "video"
    ],
    "deviceStates": [
        "idle",
        "loading",
        "paused",
        "playing",
        "seeking",
        "stopped"
    ],
    "deviceStateDelay": 0,
    "avadaKedavraAppAmount": 20,
    "disableVolumeControlRemote": false,
    "setTopBox": false,
    "discover": {
        "multicast": true,
        "unicast": [
            "192.168.2.61"
        ]
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "updateCheckLevel": "stable",
    "autoUpdate": "on",
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "platform": "AppleTVEnhanced"
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Ubuntu

### Operating System: Distribution Version

22.04.3 LTS 

### Docker

yes

### Docker Image

homebridge/homebridge

### Docker Image Tag

202-01-18

### Homebridge Version

v1.1.6

### Homebridge Config UI Version

v4.55.1

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.3.0

### Node Version

v20.11.1

### NPM Version

v10.2.4

### Python Version

v3.10.12

### PIP Version

v22.0.2

### HDMI Hops

Soundbox

### Audio Output

yes

### Same Subnet

yes

### Additional Context

no

**Comment by maxileith** [comment]
I have checked the TIVIMax app. The problem is that the app is not reporting the playing state correctly.
