### ISSUE TITLE
Sensor Updates Without Connected TV

### ISSUE THREAD

**Issue by Dan-Chin** [maxileith/homebridge-appletv-enhanced#355]
### Preconditions

- [X] The feature has not been suggested in the past or it makes sense nowadays.

### Current Situation

Sensor updates and the accessory don't register if there isn't a currently live connected TV.

### Proposed Change

Sensors and the accessory can register with the AppleTV remote press regardless of connected TV's status.

### Additional Context

I'm trying to start an automation which turns on the power to my TV via a smart plug by clicking a button on the AppleTV remote, waking the AppleTV.

I was hoping this plugin would register that the AppleTV box had come out of standby, but it only seems to register in Home as 'on' if the connected TV's power is already on.

**Comment by maxileith** [comment]
The plugin just reports the power state that the Apple TV is exposing. If the Apple TV only reports the correct state when there is a TV connected, Apple would have to fix that.

**Comment by Dan-Chin** [comment]
Okay, thanks for the information and fantastic plugin!
