### ISSUE TITLE
Set allowed times for auto update 

### ISSUE THREAD

**Issue by an-ghinid** [maxileith/homebridge-appletv-enhanced#362]
### Preconditions

- [X] The feature has not been suggested in the past or it makes sense nowadays.

### Current Situation

There is currently no direct control over when the plugin auto updates. I like to run all my updates “off hours” (3am). Thus scheduling auto update is a desired feature for me while still keeping the hands off approach of auto update.

### Proposed Change

A config option (ideally cron syntax) which allows the user to specify update windows when auto update is enabled.

**Comment by maxileith** [comment]
Hi @an-ghinid,

I have implented the feature in v1.5.0-3. You can now set the hout in which the plugin should check for updates. I have decided against cron-syntax as most homebridge users probably do not know how to write cron. So it is very basic, but it should get the job done.

I would be happy if you give me some feedback on the new feature.

**Comment by an-ghinid** [comment]
Nice one, thanks! Just updated to the beta version and set the relevant hour and will report any issues I notice.

**Comment by maxileith** [comment]
I am closing the issue as I think the feature request should be satisfied now. However, if you do experience unexpected behaviors feel free to reopen the issue.
