### ISSUE TITLE
AppleTV Remote Support

### ISSUE THREAD

**Issue by Dan-Chin** [maxileith/homebridge-appletv-enhanced#365]
### Preconditions

- [X] The feature has not been suggested in the past or it makes sense nowadays.

### Current Situation

Unable to expose physical Siri Remote as HomeKit accessory. 

### Proposed Change

HomeKit exposure of physical remote as a switch with multiple buttons to trigger automations / remaps. 

### Additional Context

Not sure if this is possible?

**Comment by maxileith** [comment]
That's not possible
