### ISSUE TITLE
failed to install on windows based homebridge

### ISSUE THREAD

**Issue by xcom1948** [maxileith/homebridge-appletv-enhanced#4]
```log
[#################.] - reify:semver: timing reifyNode:node_modules/homebridge-appletv-enh 
> @sebbo2002/node-pyatv@7.0.3 postinstall
> ./check.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code 1
npm ERR! path C:\Users\xyz\AppData\Roaming\npm\node_modules\homebridge-appletv-enhanced\node_modules\@sebbo2002\node-pyatv
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c ./check.sh

npm ERR! A complete log of this run can be found in: C:\WINDOWS\system32\config\systemprofile\AppData\Local\npm-cache\_logs\2023-11-02T19_01_13_730Z-debug-0.log
```

**Comment by maxileith** [comment]
Hi @xcom1948 ,

I am very pleased to see that you are interested in my plugin. However, I do not support non-linux based installations like Windows as stated in the README.

The error is thrown by a postinstall script of a dependency that does not support Windows.

If you really want to run it on a Windows machine, you are probably best of using Windows Subsystem for Linux ...

The better option would be to use a ARM based SBC like a Raspberry. Should also be more cost efficient in the long run as it consumes less power than most windows boxes.
