### ISSUE TITLE
Update to Python 3.12

### ISSUE THREAD

**Issue by Cohvir** [maxileith/homebridge-appletv-enhanced#433]
### Preconditions

- [X] The feature has not been suggested in the past or it makes sense nowadays.

### Current Situation

As many already reported, anything tied to Python 3.12 will trigger this error message:
`[E] Python check: Python 3.12.3 is installed. However, only Python 3.8 to 3.11 is supported.`
and will break the plugin.

### Proposed Change

I propose to update the code to support Python 3.12, as this version starts to spread quite a bit as in the case of a freshly installed Ubuntu 24.04 LTS OS.

### Additional Context

Changing Python version ONLY for the Homebridge environment can be a valid workaround, but not a real solution. (If you got instructions on how to change the Python version for Homebridge, please share them).

**Comment by maxileith** [comment]
The error message you are getting is intended. It does not actually "break" the plugin but the plugin refuses to run with Python 3.12 as it will result in other errors. The dependency pyatv does not support 3.12 yet.

Please refer to https://github.com/postlund/pyatv/issues/2182.

As a workaround I could implement a configuration option to continue on this error.

**Comment by Cohvir** [comment]
> The error message you are getting is intended. It does not actually "break" the plugin but the plugin refuses to run with Python 3.12 as it will result in real errors which an average user could not identify as an error which is caused by the wrong Python version. The dependency pyatv does not support 3.12 yet.
> 
> Please refer to [postlund/pyatv#2182](https://github.com/postlund/pyatv/issues/2182).
> 

Thank you for the clarification. I read you once wrote about changing Homebridge environment to use Python 3.10, but I have no idea how I could achieve that. 

> As a workaround I could implement a configuration option to continue on this error.

I think that would definitely increase the number of open issues

**Comment by maxileith** [comment]
@Cohvir I have added the option to specify a custom pyhton environment.

Could you please install version 1.4.0-0 and set the config parameter `pythonExecutable` to a path with a compatible version, e.g. 3.11.

Let me know if that worked out for you.

**Comment by maxileith** [comment]
As the support for Python 3.12 is not dependent on the plugin itself but rather the depdency pyatv, I will close this issue. I have implemented the solution to specify a custom compatible python interpreter in the settings. Therefore, the reason behind this issue should be solved, as you can use this plugin with a new custom interpreter on the newest ubuntu as well.

However, as soon as pyatv will support Python 3.12, the plugin will do so too.
