### ISSUE TITLE
Apple tvs doesn’t appear in homekit after delete reinstall

### ISSUE THREAD

**Issue by KNG-Makavelia** [maxileith/homebridge-appletv-enhanced#454]
### Preconditions

- [X] The support request template is not a better fit to my question

### Issue

After deleting the plugin and the Apple TV, they cannot be added back to HomeKit. Everything works normally in Homebridge, the Apple TVs are displayed, but in HomeKit they are no longer displayed for addition. I have now tried the following steps: deactivate and delete the plugin, reinstall it. Reset the remote connections on the Apple TV and re-link them. But that doesn't help. Does anyone have a solution?

**Comment by maxileith** [comment]
Have you tried this? https://github.com/maxileith/homebridge-appletv-enhanced/issues/383#issuecomment-2090119172

**Comment by KNG-Makavelia** [comment]
Thx ☺️ I will tried it as soon as possible.

**Comment by maxileith** [comment]
@KNG-Makavelia could you give me some feedback? Did you solve the problem with the source I provided? Please let me know and close the issue if your issue has been solved.

**Comment by KNG-Makavelia** [comment]
HiYes 👍 the problem is solved. I forgot to delete the previous bridge like in the source….__________________________Von meinem iPhone gesendetFreundliche Grüsse Elia KüngAm 20.06.2024 um 22:35 schrieb Maximilian Leith ***@***.***>:﻿
@KNG-Makavelia could you give me some feedback? Did you solve the problem with the source I provided? Please let me know and close the issue if your issue has been solved.
