### ISSUE TITLE
pyatv.exceptions.PairingError: Command failed: Pairing not allowed

### ISSUE THREAD

**Issue by astubbs** [maxileith/homebridge-appletv-enhanced#459]
### Preconditions

- [X] The feature has not been suggested in the past or it makes sense nowadays.

### Current Situation

I'm running Homebridge raw on Synology DSM. This plugin requires a newer version of NodeJS than what is available through the standard DSM package system.

### Proposed Change

I was wondering if it would be possible to downgrade the NodeJS dependency? I know it's definitely not ideal, but I thought you might have better insight on if the versions between change anything really important for the plugin.

### Additional Context

I'm researching how to get DSM to update the package, but it seems it is more closed than I expected.

I'll send through a support request, and these two tickets might help.

This is the Homebridge issue, where this same problem is discussed: https://github.com/homebridge/homebridge/issues/3592

**Comment by maxileith** [comment]
Could you tell me where you get stuck? During the installation process of the plugin or when starting up the plugin. Also please send me some logs when the issue occurs.

**Comment by astubbs** [comment]
Oh, sure! It's when starting the plugin.

[homebridge apple tv logs.txt](https://github.com/user-attachments/files/16075220/homebridge.apple.tv.logs.txt)

**Comment by maxileith** [comment]
Have you fulfilled this requirements from the README?

> The access of Speakers & TVs should be either set to "Everybody" or "Anybody On the Same Network" in the Home app

**Comment by maxileith** [comment]
Is `Hal 9001 (DC:56:E7:56:60:1A)` an actual Apple TV?

Also please send verbose logs.

**Comment by astubbs** [comment]
Yes, that is the name of my Apple TV.

FYI I feel like it's something to do with this: https://github.com/maxileith/homebridge-appletv-enhanced/issues/290

Here's the verbose log:
[homebridge-appletv-enhanced.log-2.txt](https://github.com/user-attachments/files/16199980/homebridge-appletv-enhanced.log-2.txt)

**Comment by astubbs** [comment]
FYI, I thought I'd try get pyatv working directly, same issue. https://github.com/postlund/pyatv/issues/2495

**Comment by astubbs** [comment]
Ah ha! Found this gem here, all good now! https://github.com/home-assistant/core/issues/113374#issuecomment-2048378316

> I was able to make the authentication work and the Home Assistant Apple TV integration setup to succeed. The issue for me was that the settings "Air Play Settings" and "Remote App Pairing" under Restrictions in Settings App was set to "Restrict". Once those were changed to "Allow" the pairing process worked.

Might be a good one to add to the readme :)

**Comment by maxileith** [comment]
Thanks for letting me know. Is I will add it to the README :)
