### ISSUE TITLE
Save „Avada Kedavra“ input name

### ISSUE THREAD

**Issue by dmncgh** [maxileith/homebridge-appletv-enhanced#46]
### Current Situation

After restarting plugin or Homebridge renamed„Avada Kedavra“ input is not configured. Hide/show option is saved tho.

### Proposed Change

Save input name „Avada Kedavra“ like the other inputs.

**Comment by maxileith** [comment]
Yep, this is not implemented yet. I will look into this.

**Comment by dmncgh** [comment]
Sorry for being late. It works. Thank you.

I came up with the idea to add Home as an input. What do you think?

**Comment by maxileith** [comment]
@dmncgh that's a good idea. I created an issue for that.

**Comment by dmncgh** [comment]
Thanks. BTW I can confirm that your plugin runs on latest MacOS. I have some log entries regarding characteristic settings:

``` 
Credentials are still valid. Continuing ...
[Apple TV Wohnstudio@@Firmware Revision] Characteristic not in required or optional characteristic section for service Television. Adding anyway.
[Apple TV Wohnstudio@idle@Configured Name] Characteristic not in required or optional characteristic section for service MotionSensor. Adding anyway.
[Apple TV Wohnstudio@paused@Configured Name] Characteristic not in required or optional characteristic section for service MotionSensor. Adding anyway.
[Apple TV Wohnstudio@playing@Configured Name] Characteristic not in required or optional characteristic section for service MotionSensor. Adding anyway.
[Apple TV Wohnstudio@music@Configured Name] Characteristic not in required or optional characteristic section for service MotionSensor. Adding anyway.
[Apple TV Wohnstudio@video@Configured Name] Characteristic not in required or optional characteristic section for service MotionSensor. Adding anyway.
```

**Comment by maxileith** [comment]
@dmncgh Thanks for the feeback. These warnings occur on Linux homebridges as well. However, I do not really understand why homebridge is logging these warning, since HomeKit definetly takes advantage of those Characterisitics. Otherwise, you would not be able to rename the motion sensors.

**Comment by dmncgh** [comment]
I see. I found this [issue](https://github.com/homebridge/homebridge/issues/3310), maybe it helps.

**Comment by maxileith** [comment]
I know how to make the warning go away. That is not the problem. I just need to remove the ConfigredName characteristic. However, then you won't be able to rename your Mmotion sensors.

**Comment by maxileith** [comment]
@dmncgh I have found a solution to fix the warnings and keep the functionality. Feel free to test this in version v0.5.1-0 beta.

**Comment by dmncgh** [comment]
Superb. Thank you.
