### ISSUE TITLE
The plugin stucks in restart loop

### ISSUE THREAD

**Issue by mkizzle2906** [maxileith/homebridge-appletv-enhanced#467]
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

I used it normally until last week everything of this plugin show No Response in Home app. I check the log and it show the plugin keeps restarting. I tried remove accessories in Home app and reinstall the plugin but nothing works

### Logs

```console
Log in attach file
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "deviceStates": [
        "playing"
    ],
    "deviceStateDelay": 0,
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "setTopBox": false,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 4,
    "updateCheckLevel": "stable",
    "deviceSpecificOverrides": [
        {
            "mac": "50:DE:06:A0:7D:3D",
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "platform": "AppleTVEnhanced",
    "_bridge": {
        "username": "0E:4D:27:5E:7D:3C",
        "port": 46458
    }
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Raspberry Pi OS

### Operating System: Distribution Version

12 (Bookworm)

### Docker

no

### Docker Image

None

### Homebridge Version

1.8.3

### Homebridge Config UI Version

v4.56.2

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.4.0

### Node Version

v20.15.0

### NPM Version

10.2.4

### Python Version

3.11.2

### PIP Version

23.0.1

### Audio Output

no

### Same Subnet

yes

### Additional Context

[homebridge-appletv-enhanced.log.txt](https://github.com/user-attachments/files/15929429/homebridge-appletv-enhanced.log.txt)

**Comment by mkizzle2906** [comment]
Anyone know how to fix this ? I tried removing then reinstall the plugin, even format sd card and reinstall the whole homebridge but this error still happens

**Comment by maxileith** [comment]
Please send verbose logs.

**Comment by mkizzle2906** [comment]
> Please send verbose logs.

how can I get it ?

**Comment by maxileith** [comment]
Set the log level to verbose in the settings

**Comment by mkizzle2906** [comment]
here it is[
[homebridge-appletv-enhanced.log.txt](https://github.com/user-attachments/files/15937553/homebridge-appletv-enhanced.log.txt)
](url)

**Comment by philmue1988** [comment]
Facing the Same Problem as soon as i have more than 1 ATV connected

**Comment by maxileith** [comment]
@mkizzle2906 Could you please send me the output of `ls -la /var/lib/homebridge/appletv-enhanced/50DE06A07D3D`

**Comment by mkizzle2906** [comment]
> ls -la /var/lib/homebridge/appletv-enhanced/50DE06A07D3D

Here it is

total 24
drwxr-xr-x 2 pi pi 4096 Jun 22 04:19 .
drwxr-xr-x 4 pi pi 4096 Jun 22 04:29 ..
-rw-r--r-- 1 pi pi    0 Jun 22 04:19 apps.json
-rw-r--r-- 1 pi pi   38 Jun 22 04:19 common.json
-rw-r--r-- 1 pi pi  275 Jun 22 04:19 credentials.txt
-rw-r--r-- 1 pi pi    2 Jun 22 04:19 deviceStates.json
-rw-r--r-- 1 pi pi    2 Jun 22 04:19 mediaTypes.json

**Comment by maxileith** [comment]
Which user are you using to run homebridge?

**Comment by mkizzle2906** [comment]
> Which user are you using to run homebridge?

I'm using pi

**Comment by maxileith** [comment]
What's the content of `/var/lib/homebridge/appletv-enhanced/50DE06A07D3D/appConfigs.json`?

**Comment by mkizzle2906** [comment]
> /var/lib/homebridge/appletv-enhanced/50DE06A07D3D/

there is no appConfigs.json. There are only apps.json  common.json  credentials.txt  deviceStates.json  mediaTypes.json

**Comment by mkizzle2906** [comment]
> What's the content of `/var/lib/homebridge/appletv-enhanced/50DE06A07D3D/appConfigs.json`?

is there any way to fix it ?

**Comment by maxileith** [comment]
Sorry my bad, could you send the content of `apps.json`?

**Comment by mkizzle2906** [comment]
> /var/lib/homebridge/appletv-enhanced/50DE06A07D3D/

there is nothing there 🥲

**Comment by mkizzle2906** [comment]
> Sorry my bad, could you send the content of `apps.json`?

there is nothing in that file 🥲

**Comment by maxileith** [comment]
Can you stop the plugin, remove the file and restart the plugin?

**Comment by mkizzle2906** [comment]
> Can you stop the plugin, remove the file and restart the plugin?

remove that apps.json file or the whole folder ?

**Comment by mkizzle2906** [comment]
> Can you stop the plugin, remove the file and restart the plugin?

hey I tried remove that folder and restart the plugin. The log shows the paring link and I follow that enter the pin, then it said add the apple tv... manually in Home app. I add it by enter the code in home app but it doesn't show the apple TV to add

https://github.com/maxileith/homebridge-appletv-enhanced/assets/32402155/c7dc5ecc-7ec7-4247-92e9-46d56683d1a2

Here is the log
[homebridge-appletv-enhanced.log (1).txt](https://github.com/user-attachments/files/16041335/homebridge-appletv-enhanced.log.1.txt)

**Comment by maxileith** [comment]
Hi @mkizzle2906,

thank you for the response. I have fixed the bug where the plugin ends up in an infinte restart loop when there are empty config files like `apps.json` in version v.1.4.3-0
