### ISSUE TITLE
the app is unknown,what happened

### ISSUE THREAD

**Issue by Yumega** [maxileith/homebridge-appletv-enhanced#468]
### Preconditions

- [X] The support request template is not a better fit to my question

### Issue

it works, but there is a log 

(EC:A9:07:1B:46:13): Could not update the input to com.apple.SoundScapes since the app is unknown.

**Comment by maxileith** [comment]
Restart the plugin. I assume that you just installed this app. After restarting the plugin will refresh the app list and the app will be known.

**Comment by maxileith** [comment]
Please open a support request issue for that. The template will ask for everything I need to dig into this problem.
