### ISSUE TITLE
Netflix play title not working correctly

### ISSUE THREAD

**Issue by thud06** [maxileith/homebridge-appletv-enhanced#510]
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

Hello! When trying to use the custom input URIs i try to play https://www.netflix.com/watch/81232320, however it just opens the netflix app but does not play the show

### Logs

```console
n/a
```

### Configuration

```JSON
{
            "name": "Apple TV Enhanced",
            "deviceStateDelay": 0,
            "remoteKeysAsSwitch": [
                "down",
                "home",
                "left",
                "play",
                "right",
                "select",
                "turn_off",
                "turn_on",
                "up"
            ],
            "avadaKedavraAppAmount": 15,
            "customInputURIs": [
                "https://www.netflix.com/watch/81232320",
                "https://www.netflix.com/watch/81001554"
            ],
            "disableVolumeControlRemote": false,
            "absoluteVolumeControl": true,
            "setTopBox": false,
            "discover": {
                "multicast": true
            },
            "forceVenvRecreate": false,
            "logLevel": 3,
            "updateCheckLevel": "stable",
            "updateCheckTime": 3,
            "deviceSpecificOverrides": [
                {
                    "overrideMediaTypes": false,
                    "overrideDeviceStates": false,
                    "overrideDeviceStateDelay": false,
                    "deviceStateDelay": 0,
                    "overrideRemoteKeysAsSwitch": false,
                    "overrideAvadaKedavraAppAmount": false,
                    "avadaKedavraAppAmount": 15,
                    "overrideCustomInputURIs": false,
                    "overrideDisableVolumeControlRemote": false,
                    "disableVolumeControlRemote": false,
                    "overrideAbsoluteVolumeControl": false,
                    "absoluteVolumeControl": false,
                    "overrideSetTopBox": false,
                    "setTopBox": false
                }
            ],
            "platform": "AppleTVEnhanced"
        }
    ]
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Raspbian GNU/Linux Bullseye (11)

### Operating System: Distribution Version

Raspbian GNU/Linux Bullseye (11)

### Docker

no

### Docker Image

None

### Homebridge Version

1.8.4

### Homebridge Config UI Version

4.56.4

### Homebridge Storage Path

/var/home

### Homebridge Apple TV Enhanced Version

v1.5.0

### Node Version

v20.16.0

### NPM Version

10.8.1

### Python Version

Python 3.9.2

### PIP Version

pip 20.3.4

### Audio Output

no

### Same Subnet

yes

**Comment by maxileith** [comment]
Provide debug logs.
