### ISSUE TITLE
Apple TV Enhanced and video signal of projector - Problem with automation, any ideas ?

### ISSUE THREAD

**Issue by alexis2110** [maxileith/homebridge-appletv-enhanced#545]
### Preconditions

- [X] The support request template is not a better fit to my question

### Issue

Hi there,

I need help with Homekit automation via accessories running on Homebridge. I have a cinema setup consisting of :

1 Apple TV (Apple TV Enhanced plugin)
1 video projector (RF code via Broadlink RM plugin )
1 sound bar (RF code via Broadlink RM plugin)
1 motorised screen (RF code via Broadlink RM plugin)

Everything works fine independently. But when I try to do this automation :

If "Apple TV" turns on (with physical remote) (it turns on Homekit device)
Then Turn on "Projector", Turn on "Soundbar" and Open "Screen".

The problem is with the video signal received by the Apple TV from my projector.

The Apple TV Enhanced plugin works very well and when I turn on my Apple TV with my remote control, it changes the status on Homekit, a **few seconds later my projector turns on but it cuts the video signal to search and select the default source (Input 1 = Apple tv) and that's when the status of the Apple TV changes on Homekit** (it turn off) and causes a problem in my automation because it's start the other automation (When Apple TV, close all)

Any ideas how to solve this problem? Do you have a feature to solve this action ? 

(As i understand, the statut of the Apple TV on homekit depends of the video signal. I tried to turn on apple tv without turn on screen or tv and the homekit device doesn't turn on.)

Thanks !

**Comment by maxileith** [comment]
Can you post verbose logs?
