### ISSUE TITLE
Automation conflicts caused by the motion sensor

### ISSUE THREAD

**Issue by Mercy0310** [maxileith/homebridge-appletv-enhanced#552]
### Preconditions

- [X] The support request template is not a better fit to my question

### Issue

Thank you to the creator; this project is very useful. I noticed that when I fast-forward media using Infuse, the motion sensor's status shows as "paused" instead of "seeking." This causes my automation to mistakenly interpret fast-forwarding as pausing, which affects the execution of the automation. Is there a solution to this issue?

**Comment by maxileith** [comment]
That's an issue of infuse reporting the wrong status. There is nothing I can do from my side.
