### ISSUE TITLE
Issue with AppleTV-Enhanced, not sure if it's a bug or configuration...

### ISSUE THREAD

**Issue by nilthing9** [maxileith/homebridge-appletv-enhanced#558]
### Preconditions

- [X] The support request template is not a better fit to my question

### Issue

Hello,

I have been using the AppleTV-Enhanced plugin for a while now. 
It allowed me to create an automation to turn on my TV and the surround sound speakers when someone pressed the power button on the Apple remote. 

This was working well until recently when I experienced a crash on my Raspberry Pi. 
Since then I have not been successful in recreating my automation. 

I have reinstalled the latest version of the OS (Raspberrypios lite Bookworm 64 bit) and reinstalled Homebridge and my plugins from scratch. (I had backups, but they seemed to be causing me more problems so I gave up.)
I have followed the instructions to install it correctly. 

In configuring AppleTV-Enhanced I have made the power on and off toggles available.  I created the automation in Apple Home to turn on the switches when triggered by a power button press. Homebridge sees the button presses and the state changes. But the automation doesn't appear to run. 

If I test the automation in Home, it turns on the TV and speakers as expected.

One thing I seem to recall, was previously there was an option: Power on/off 

So before I open a ticket, is this a bug or a configuration thing?  I cannot see any obvious errors in the logs, except the occasional "loss of connection" which then reconnects... 

Many thanks

**Comment by maxileith** [comment]
> I have made the power on and off toggles available

What do you mean with that. You can expose remote control buttons as switches with the plugin but they are "write-only". If you want to trigger an automation based on the power state of your Apple TV ... just use the power state. Setup the automation trigger on the Apple TV device itself, not a switch.

**Comment by nilthing9** [comment]
Hi,
Thanks for replying. Seems user/config error (which isn't surprising).
To explain what I meant by the power on and off toggles -  I mean I selected the switches "Turn_off" & "Turn_on" in the >Plugin config>Basics>Remote Keys as Switches section. 

I assumed that the Apple TV device would see the "Power_on" as triggers to run an automation.

At this point in time, they do not appear to do this. 

I don't understand why this is the case. I seem to recall in an earlier version of your app, there was also a switch that showed the power button as a boolian input Power on/off, which if my memory serves was the way I got this automation to work before. But I may be mis-remembering this.

As to using the powerstate of my Apple TV device to enable an automation - I have not been able yet to get that to work. 

Could you add a bit more detail to help me figure this out, because it is making no sense to me? 

I've enabled all the power state options in the plugin config:

<img width="790" alt="Screenshot 2024-08-29 at 13 02 22" src="https://github.com/user-attachments/assets/394e21ff-80d4-4f9b-92fe-df738ee60aa2">

and set automations in the Apple Home>Automation>Add Automation>A Sensor Detects Something. 
So far using this input they don't seem to trigger anything when I press the power button on my apple remote.

Thanks in advance for any advice.

**Comment by nilthing9** [comment]
Aaaahhhhh. Following your instructtions it now works. Thanks for taking the time to help me.

**Comment by lgrachov** [comment]
In the latest iOS 26 update, the Apple TV accessory no longer shows up in the **An Accessory is Controlled** trigger. I can't find any workarounds for this. Any fixes?
