### ISSUE TITLE
Raspberry Pi does not have OpenSSL 3 available via apt

### ISSUE THREAD

**Issue by psycoticninja** [maxileith/homebridge-appletv-enhanced#573]
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

It looks like that v1.6.0 has a requirement of OpenSSL 3.0 minimum. Raspbian OS Lite (or at least for me that OS) you cannot install anything higher than the below using apt.  I would prefer to not have to build this from source.

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
openssl is already the newest version (1.1.1w-0+deb11u1+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Due to this issue I cannot use the plugin. If I try to downgrade it, there looks to be some auto upgrade checker in place as the moment it restarts with 1.5.2 it then upgrades to 1.6.0 and I am stuck.

```
[29/08/2024, 07:42:09] [Apple TV Enhanced] [I] Update check: Attempting to update AppleTV Enhanced to version 1.6.0
[29/08/2024, 07:42:09] [Apple TV Enhanced] [I] Update check: CMD: npm "install" "--no-audit" "--no-fund" "--global-style" "--save" "homebridge-appletv-enhanced@1.6.0" (cwd: /var/lib/homebridge)
```

### Logs

```console
Logs above.
```

### Configuration

```JSON
Not applicable.
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Debian GNU/Linux - (it is Raspbian OS Lite)

### Operating System: Distribution Version

11 (bullseye)

### Docker

no

### Docker Image

None

### Homebridge Version

1.8.4

### Homebridge Config UI Version

v4.57.1

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.6.0

### Node Version

v20.16.0

### NPM Version

10.8.1

### Python Version

3.9.2

### PIP Version

20.3.4

### Audio Output

no

### Same Subnet

yes

**Comment by maxileith** [comment]
@psycoticninja you can deactivate the auto updater in the settings if you want to stay on 1.5.2. The better option would probably be to update your os from Bullseye (11) to Bookworm (12).
