### ISSUE TITLE
missing venv package on HyperV image

### ISSUE THREAD

**Issue by EyadElshaer** [maxileith/homebridge-appletv-enhanced#575]
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [ ] There is currently no other opened issue that matches my question
- [ ] I cannot find any answer to my question in GitHub discussions

### Current Situation

I recently downloaded the Apple TV enhanced Plugin but I get a this error message and I don't know what should I do.
I am using a windows 11 machine using Oracle VM Machine.

![Screenshot 2024-08-30 104742](https://github.com/user-attachments/assets/7ad68172-9849-4c5d-be5a-c64dfc66e463)

### Logs

```console
[8/30/2024, 11:06:03 AM] [Apple TV Enhanced] [I] Update check: You are using the latest version of AppleTV Enhanced (excluding betas): 1.6.0
[8/30/2024, 11:06:03 AM] [Apple TV Enhanced] [I] Python check: Starting python check.
[8/30/2024, 11:06:03 AM] [Apple TV Enhanced] [I] Python check: plugin dir exists.
[8/30/2024, 11:06:03 AM] [Apple TV Enhanced] [I] Python check: Python 3.8.10 is installed and supported by the plugin.
[8/30/2024, 11:06:03 AM] [Apple TV Enhanced] [I] Python check: Virtual python environment is not present. Creating now ...
[8/30/2024, 11:06:03 AM] [Apple TV Enhanced] [E] Python check: virtualenv python module is not installed. If you have installed homebridge via the apt package manager, update the homebridge apt package to 1.1.4 or above (this applies for installations based on the Raspberry Pi OS image as well). When using the official docker image, update the image to version 2023-11-28 or above. Otherwise install the python virtualenv module manually.
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "mediaTypes": [
        "music",
        "tv",
        "video"
    ],
    "deviceStates": [
        "loading",
        "paused",
        "playing"
    ],
    "deviceStateDelay": 0,
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "absoluteVolumeControl": false,
    "setTopBox": true,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "updateCheckLevel": "stable",
    "updateCheckTime": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideAbsoluteVolumeControl": false,
            "absoluteVolumeControl": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "platform": "AppleTVEnhanced"
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Windows Virtual Machine (Oracle VM)

### Operating System: Distribution Version

20.04.5

### Docker

no

### Docker Image

None

### Docker Image Tag

bash: docker: command not found

### Homebridge Version

1.8.4

### Homebridge Config UI Version

4.57.1

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.6.0

### Node Version

v20.17.0

### NPM Version

10.8.2

### Python Version

3.8.10

### PIP Version

20.0.2

### HDMI Hops

Apple OTT/ Philips Home Theater

### Audio Output

yes

### Same Subnet

yes

**Comment by maxileith** [comment]
Which OS are you running inside the VM? I guess Ubuntu based on the version 20.04.5 that you have provided. If you have installed homebridge via apt, just update to the latest apt package which will install all requirements automatically.

**Comment by EyadElshaer** [comment]
> Which OS are you running inside the VM? I guess Ubuntu based on the version 20.04.5 that you have provided. If you have installed homebridge via apt, just update to the latest apt package which will install all requirements automatically.

No I installed Home bridge using the windows installation guide with the iso image

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10-Using-Hyper-V

I got the iso image from this link

**Comment by EyadElshaer** [comment]
> Which OS are you running inside the VM? I guess Ubuntu based on the version 20.04.5 that you have provided. If you have installed homebridge via apt, just update to the latest apt package which will install all requirements automatically.

when I tried to download virtualenv it still doesn't want to work
![image](https://github.com/user-attachments/assets/b9135a9e-7c5d-4a91-940b-828420905c47)

**Comment by maxileith** [comment]
> > Which OS are you running inside the VM? I guess Ubuntu based on the version 20.04.5 that you have provided. If you have installed homebridge via apt, just update to the latest apt package which will install all requirements automatically.
> 
> No I installed Home bridge using the windows installation guide with the iso image
> 
> https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10-Using-Hyper-V
> 
> I got the iso image from this link

I wasn't aware that there is such an image. I will take a look at the image and check what is required to get the plugin up and running with that image when I get the time to do it. I'll give you an update here.

**Comment by EyadElshaer** [comment]
> > > Which OS are you running inside the VM? I guess Ubuntu based on the version 20.04.5 that you have provided. If you have installed homebridge via apt, just update to the latest apt package which will install all requirements automatically.
> > 
> > No I installed Home bridge using the windows installation guide with the iso image
> > 
> > https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10-Using-Hyper-V
> > 
> > I got the iso image from this link
> 
> I wasn't aware that there is such an image. I will take a look at the image and check what is required to get the plugin up and running with that image when I get the time to do it. I'll give you an update here.

Sure man take your time

**Comment by maxileith** [comment]
You may want to take a look at this issue that I have just created: https://github.com/homebridge/homebridge-vm-image/issues/5

As an alternative, you can of course just update your VM / docker container.

**Comment by maxileith** [comment]
I don't think we are getting an answer on that issue I opened within the repository of the VM image. However, you can install the virtualenv package by running `pip install venv`.

**Comment by maxileith** [comment]
Closing that issue for now. If you need further advice feel free to reopen.

**Comment by nrc2358** [comment]
Got the same issue after updating the plugin. Upgraded python and venv but issue did not resolve until downgrading plugin first. After a successful venv build on the downgraded plugin, upgrading to the current plugin version worked.

**Comment by darkaeden** [comment]
> Got the same issue after updating the plugin. Upgraded python and venv but issue did not resolve until downgrading plugin first. After a successful venv build on the downgraded plugin, upgrading to the current plugin version worked.

I have the same problem, also running HB on a virtualbox in Win11 pro.
Whatever update of python i do in HB Terminal, it succesfully install it, but it always show that pythong version is 3.8.
Mind to share to which plugin version number you downgraded?
First downgrade plugin version, then retry pything/venv upgrade from terminal, then upgrade to new plugin version?
Thanks

**Comment by EyadElshaer** [comment]
> Got the same issue after updating the plugin. Upgraded python and venv but issue did not resolve until downgrading plugin first. After a successful venv build on the downgraded plugin, upgrading to the current plugin version worked.

Honestly I made a partition in my laptop and downloaded and installed Ubuntu Server on it which fixed the issue and Apple TV enhanced plugin works great

**Comment by EyadElshaer** [comment]
> Got the same issue after updating the plugin. Upgraded python and venv but issue did not resolve until downgrading plugin first. After a successful venv build on the downgraded plugin, upgrading to the current plugin version worked.

You can try installing Ubuntu Server on a virtual box and downloading HomeBridge on it if you really want windows
