### ISSUE TITLE
Change from Set-top-box exposing

### ISSUE THREAD

**Issue by MirkoKas** [maxileith/homebridge-appletv-enhanced#61]
First of all: Your plugin is awesome. Looked for something like this for a long time!

In the latest changelog you wrote:

Apple TV is now exposed as an actual Apple TV, not a Set-Top-Box (**requires you to repair your Apple TV in the Home app** if you want to see the change. However, you do not need to repair your Apple TV, you just won't see the change)

What do you mean by „repair“? Delete the device and re-add?

**Comment by maxileith** [comment]
@MirkoKas With repairing I mean to remove the device from the home app and add it again to the home app. Repair is not meant the mechanic way 👨‍🔧

**Comment by MirkoKas** [comment]
ok - thx. That's what I expected, but as I have quite a few automations with the Apple TV I will stick for now with the set-top-box icon. :-)
