### ISSUE TITLE
[Apple TV Enhanced] Python check:  is installed. However, only Python 3.8 to 3.11 is supported.

### ISSUE THREAD

**Issue by LaurentCole** [maxileith/homebridge-appletv-enhanced#62]
### Current Situation

Hi,
I'm trying your plugin to find out what is possible to do with it, though it looks great.

This issue came up in the logs :
[Apple TV Enhanced] Python check:  is installed. However, only Python 3.8 to 3.11 is supported.

What should I do ?

Force Venu Recréation is checked.

Thanks.

### Logs

```Markdown
[Apple TV Enhanced] Python check:  is installed. However, only Python 3.8 to 3.11 is supported.
```

### Configuration

```JSON
{
    "mediaTypes": [
        "music",
        "video"
    ],
    "deviceStates": [
        "paused",
        "playing"
    ],
    "remoteKeysAsSwitch": [],
    "customInputURIs": [],
    "discover": {
        "unicast": [
            "192.168.1.123"
        ],
        "blacklist": [
            "c8:69:cd:42:da:bd / 192.168.1.96"
        ],
        "multicast": true
    },
    "name": "Apple TV Enhanced",
    "avadaKedavraAppAmount": 15,
    "forceVenvRecreate": true,
    "_bridge": {
        "username": "0E:C6:46:ED:90:52",
        "port": 47152
    },
    "platform": "AppleTVEnhanced"
}
```

### Environment

- OS: MacOS Sonoma
- Docker:
- Homebridge: 1.7.0
- Apple TV Enhanced: 0.5.0
- Node: 20.9.0
- npm: 
- Python:

**Comment by LaurentCole** [comment]
I managed to install python now I have this : 

[Apple TV Enhanced] Platform: Error: Unable to execute request 4S: /Users/plex/.homebridge/appletv-enhanced/.venv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

**Comment by LaurentCole** [comment]
In the WARNING I have this :

'darwin 23.1.0' is not supported by the plugin Homebridge Apple TV Enhanced. You will likely experience problems. However, you may get the plugin to work on your system.

Newbie here so if you could help me to install openssl 1.1.1+ that would be great.

Thanks

**Comment by maxileith** [comment]
Darwin means that you are using MacOS which I do not officially support. Since I am not a Mac user I do not have experience on how to install packages. On Linux I would tell you to just use your package manager.

You should have some basic knowledge like installing packages on the OS you are using.

**Comment by mrmaximas** [comment]
> In the WARNING I have this :
> 
> 'darwin 23.1.0' is not supported by the plugin Homebridge Apple TV Enhanced. You will likely experience problems. However, you may get the plugin to work on your system.
> 
> Newbie here so if you could help me to install openssl 1.1.1+ that would be great.
> 
> Thanks

brew install openssl@1.1

**Comment by jeanofthedead** [comment]
Looks like OpenSSL 1.1 is deprecated and will be disabled on Oct 24, 2024.
