### ISSUE TITLE
Option to disable remote per Apple TV

### ISSUE THREAD

**Issue by ahwman** [maxileith/homebridge-appletv-enhanced#66]
### Current Situation

It would be helpful if possible to have the option to disable the control center remote for specific Apple TV’s or globally if it would be easier to implement.  This would help keep the clutter down for people like myself who have many Apple TV’s… 😀 

### Proposed Change

Solution highlighted above.

**Comment by maxileith** [comment]
This is not possible due to HoneKit limitations. Every Television device needs to expose a remote.
