### ISSUE TITLE
Device on/off state

### ISSUE THREAD

**Issue by kirkrove** [maxileith/homebridge-appletv-enhanced#664]
### Preconditions

- [X] The support request template is not a better fit to my question

### Issue

When I turn my Apple TV off, the plugin Shows AppleTV as active still. 

Is the expectation that we would toggle the AppleTV bridge on/off to get automation or is it suppose to sync up with the state of the actual Apple TV? ie if I use AppleTV remote to turn on / off the device that the plugin state would update.

**Comment by maxileith** [comment]
Have you read the following form the README?

> If using audio output devices other than the Apple TV itself, the Apple TV is always reported as powered on. This is a known issue of the dependency [pyatv](https://pyatv.dev/), see https://github.com/postlund/pyatv/issues/1667. As a result, the Apple TV device will only be shown as off in HomeKit when powered off via the Apple TV device in HomeKit. After restarting the plugin the device will always be shown as on.

**Comment by kirkrove** [comment]
Ah shoot, I did read that part but didn't think much of it until you mentioned it just now. 🤦🏻‍♂️

**Comment by maxileith** [comment]
> Ah shoot, I did read that part but didn't think much of it until you mentioned it just now. 🤦🏻‍♂️

Yeah, that a pretty silly limitation ... however, nothing that I can fix.

I guess it's a good excuse for a good sound system 😂

**Comment by kirkrove** [comment]
hah, I wish. Theater audio set up is a pain. I suppose I could create scenes to turn the plug in on / off which then can trigger my other automations. Will give that a try.
