### ISSUE TITLE
Auto-Update not working: Could not determine the path where to install the plugin since the environment variable UIX_CUSTOM_PLUGIN_PATH is not set

### ISSUE THREAD

**Issue by mensa84** [maxileith/homebridge-appletv-enhanced#700]
### Preconditions

- [X] The support request template is not a better fit to my question

### Issue

Hi,
I wanted to use Auto-Update feature, but it seems to not work:

`Auto-Update not working: Could not determine the path where to install the plugin since the environment variable UIX_CUSTOM_PLUGIN_PATH is not set`

Can just the default path be used or where should I configure that path?

**Comment by maxileith** [comment]
Did you install homebridge with npm globally?

**Comment by mensa84** [comment]
> Did you install homebridge with npm globally?

I don't know anymore, sorry. How may I check?

**Comment by maxileith** [comment]
How have you installed your homebridge? Did you install it via the Raspberry Pi image? Which OS is your homebridge running on? Do you have the installation instructions still?

**Comment by mensa84** [comment]
I am running it on Debian 12.7 and I think I installed homebridge by `apt install homebridge` like described in the instructions: https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux

**Comment by maxileith** [comment]
Since there are various installation methods for homebridge, my plugin only auto updates when it is very sure about how the plugin and homebridge was installed. If the plugin cannot reliably determine how the plugin und homebridge was installed it cannot auto update it reliably. So instead of risking to screw up the installation, the plugin won't auto update.

**Comment by mensa84** [comment]
> Since there are various installation methods for homebridge, my plugin only auto updates when it is very sure about how the plugin and homebridge was installed.

How can I help the plugin to be sure?
I am sure, that I installed Homebridge by apt install and the plugin itself was installed by Homebridge UI.

**Comment by maxileith** [comment]
Set the UIX_CUSTOM_PLUGIN_PATH environment variable to the path of the plugin installation location.
