### ISSUE TITLE
Web UI Remote Control

### ISSUE THREAD

**Issue by Johannp02180** [maxileith/homebridge-appletv-enhanced#701]
### Preconditions

- [X] The feature has not been suggested in the past or it makes sense nowadays.

### Current Situation

At the moment it is controlled from homekit/apple tv remote app. I was trying to control my TV remotely (to turn it on for my doggo) and wasn't able to.

### Proposed Change

I saw that there is already a web server for the pairing code which looks great. An option to enable the web server for a remote UI that incorporates the best features of this plugin vs the apple tv remote app so that it can be controlled from the browser on my phone.

### Additional Context

N/A

**Comment by maxileith** [comment]
You can use Apple Home remotely if you have a HomeHub in your network.

Another option would be to use the "Accessories" page of the homebridge ui.

I am not going to develop a Web GUI for the plugin as this seems redundant to me.
