### ISSUE TITLE
Frequent Lost Connection and Reestablished issues

### ISSUE THREAD

**Issue by threeonparfive** [maxileith/homebridge-appletv-enhanced#716]
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

I'm getting frequent connection losses which almost always happens while watching something.  This is on 3rd generation ATV 4K.  The ATV is connected via GigE as is my Homebridge server running via Docker image on a Synology DS220+.  Both are connected via GigE on a flat (single subnet) network.  The Synology has over 2GB RAM free at all times and CPU load is very low at all times.  The ATV is currently running tvOS 18 but this issue has been happening before upgrading to tvOS 18 and has persisted through various versions of the plugin.

The issue is typically no bother except when it occurs seemingly at exactly the time I'm "powering off" the ATV via the original remote.  My only reason for using the plugin is to catch the "power off" even to trigger control of various lights so when it occurs at these times, my automation fails to trigger.  It doesn't happen every time I power off, or at least not such that it causes my automation to fail to run.

The connection losses do seem to occasionally happen while there's no interaction with the ATV (ie. in the middle of something actually being played).  Reviewing the logs, it appears that most of the connection losses occur when switching between apps.  As I think about my nightly pattern and tie it back to the logs, I do see some consistency in many of the connection losses.  Unlike my wife, I always exit whatever app we are watching, back to the Home Screen, before powering off the ATV.  I also tend to return the "cursor" back to our primary used app (YouTube TV) and "park" the cursor there, without actually launching the app, then power off.  I'm certain there are times where I power off more quickly and other times when it may be a few seconds before I power off.  Perhaps when I take more time in doing so, the connection has time to reestablish to catch the power off event and successfully trigger the automation?  Nonetheless, if the connection losses weren't happening at all, this would never be an issue.

### Logs

```console
log attached
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "deviceStateDelay": 0,
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "absoluteVolumeControl": false,
    "discover": {
        "multicast": true,
        "blacklist": [
            "192.168.1.52",
            "08:66:98:ED:B8:AB",
            "192.168.1.124",
            "08:66:98:D9:92:78"
        ]
    },
    "forceVenvRecreate": false,
    "logLevel": 3,
    "updateCheckLevel": "stable",
    "updateCheckTime": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideAbsoluteVolumeControl": false,
            "absoluteVolumeControl": false
        }
    ],
    "_bridge": {
        "username": "0E:23:05:E0:89:CE",
        "port": 33401
    },
    "platform": "AppleTVEnhanced"
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Ubuntu (running command in HB terminal

### Operating System: Distribution Version

22.04.5 LTS (Jammy Jellyfish) in HB terminal, Synology OS is DSM 7.2.2-72806

### Docker

no

### Docker Image

None

### Docker Image Tag

2024-10-25

### Homebridge Version

1.8.5

### Homebridge Config UI Version

v4.62.0

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.9.1

### Node Version

v20.18.0

### NPM Version

10.8.2

### Python Version

3.10.12

### PIP Version

22.0.2

### HDMI Hops

Polk Magnifi Max AX sound bar

### Audio Output

no

### Same Subnet

yes

### Additional Context

[homebridge-appletv-enhanced.log.txt](https://github.com/user-attachments/files/17571092/homebridge-appletv-enhanced.log.txt)

Log is not in debug mode because I didn't have it in debug at the time the most recent issue occurred.  If necessary, I can put in debug and attempt to reproduce.

I'm leaving the MAC addresses in the log to make it easy to tell the difference between our main TV (which my automations are tied to) and a bedroom unit (which is WiFi connected) but the bedroom unit isn't currently used for any automations thus it's a non-issue on that one.  Also, the times to look at would be those happening sometime after 9pm, typically closer to 9:30-10pm, as that's our watching pattern and when an automation is supposed to trigger on power off.

**Comment by threeonparfive** [comment]
After looking over the attached log again, I noticed one obvious issue that I had overlooked earlier.  On 10/28 @ 9:31pm, you can see where I exited the app I was previously in (Plex beginning at 8:10pm), back to the Home Screen, parked the cursor on the YouTube TV app icon, then powered off.  My automation worked that night and there likely was a 7sec or so pause between exiting Plex and turning off the ATV.

If you look at 10/29 @ 9:55pm, you can see a similar pattern, though this time exiting Apple's app, but you never see the "active state off" message that should have followed the "current app....YouTube tv" message.   And 10/29 was one of the nights that my automation failed to run.

It definitely seems that the exiting of apps is where the connection losses are coming from and the connection not reestablishing in time before I turn it off causes that state change to be missed and ultimately my automation to not trigger.

**Comment by maxileith** [comment]
> After looking over the attached log again, I noticed one obvious issue that I had overlooked earlier. On 10/28 @ 9:31pm, you can see where I exited the app I was previously in (Plex beginning at 8:10pm), back to the Home Screen, parked the cursor on the YouTube TV app icon, then powered off. My automation worked that night and there likely was a 7sec or so pause between exiting Plex and turning off the ATV.
> 
> If you look at 10/29 @ 9:55pm, you can see a similar pattern, though this time exiting Apple's app, but you never see the "active state off" message that should have followed the "current app....YouTube tv" message. And 10/29 was one of the nights that my automation failed to run.
> 
> It definitely seems that the exiting of apps is where the connection losses are coming from and the connection not reestablishing in time before I turn it off causes that state change to be missed and ultimately my automation to not trigger.

Honestly, I think you are overthinking it a bit. There are times where the plugin is loosing connection every few minutes. It is likely a problem with your network. In any case, the plugin is utilizing the project [pyatv](https://github.com/postlund/pyatv) which is doing the heavy lifting in the background. So if pyatv looses the conneciton, my plugin just kills the old process and spins up another process of `atvscript push_update`. So if you think the root cause is not your network, go ahead and open an issue [here](https://github.com/postlund/pyatv/issues).
