### ISSUE TITLE
Plugin stuck in a boot loop

### ISSUE THREAD

**Issue by njuart** [maxileith/homebridge-appletv-enhanced#766]
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

All of a sudden plugin stuck in a boot loop

[apps.json](https://github.com/user-attachments/files/17882296/apps.json)
### Logs

```console
attached in Additional Context
```

### Configuration

```JSON
{
            "name": "homebridge-appletv-enhanced",
            "mediaTypes": [
                "music",
                "video"
            ],
            "deviceStates": [
                "paused",
                "playing"
            ],
            "deviceStateDelay": 0,
            "remoteKeysAsSwitch": [
                "home",
                "menu",
                "play_pause"
            ],
            "avadaKedavraAppAmount": 15,
            "disableVolumeControlRemote": false,
            "absoluteVolumeControl": false,
            "setTopBox": true,
            "discover": {
                "multicast": true
            },
            "forceVenvRecreate": false,
            "logLevel": 3,
            "updateCheckLevel": "stable",
            "updateCheckTime": 3,
            "deviceSpecificOverrides": [
                {
                    "overrideMediaTypes": false,
                    "overrideDeviceStates": false,
                    "overrideDeviceStateDelay": false,
                    "deviceStateDelay": 0,
                    "overrideRemoteKeysAsSwitch": false,
                    "overrideAvadaKedavraAppAmount": false,
                    "avadaKedavraAppAmount": 15,
                    "overrideCustomInputURIs": false,
                    "overrideDisableVolumeControlRemote": false,
                    "disableVolumeControlRemote": false,
                    "overrideAbsoluteVolumeControl": false,
                    "absoluteVolumeControl": false,
                    "overrideSetTopBox": false,
                    "setTopBox": false
                }
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Raspberry Pi OS

### Operating System: Distribution Version

11 (bullseye)

### Docker

no

### Docker Image

None

### Homebridge Version

1.8.5

### Homebridge Config UI Version

4.63.0

### Homebridge Storage Path

/var/lib/hombridge

### Homebridge Apple TV Enhanced Version

1.10.1

### Node Version

20.18.0

### NPM Version

10.8.2

### Python Version

3.9.2

### PIP Version

22.3.1

### HDMI Hops

AV Receiver

### Audio Output

no

### Same Subnet

yes

### Additional Context

![IMG_9675](https://github.com/user-attachments/assets/dc9ae687-5410-4d34-8b63-410d86a286f8)

**Comment by maxileith** [comment]
For context https://discord.com/channels/432663330281226270/1289375141872275476/1309448645334007881

**Comment by maxileith** [comment]
Closing since @njuart already deleted apps.json which makes it hard to debug. https://discord.com/channels/432663330281226270/1289375141872275476/1309982964838432832
