### ISSUE TITLE
BUG: Home App Crashes When Setting up Automation

### ISSUE THREAD

**Issue by ukiews** [maxileith/homebridge-appletv-enhanced#780]
### Analysis

I have an automation setup in the Home app where all actions are within a shortcut.
When I go to select the ATV in order to select input source (circled in image), the Home app crashes every time.
Tried this on MacOS and iOS. Home app crashes on both. Any new automation that requires source selection, crashes the Hope app during setup process.
<img width="509" alt="Screenshot 2024-12-02 at 11 46 21" src="https://github.com/user-attachments/assets/111e5010-2119-4d27-92c8-75f9c6c0de80">

### Expected Behavior

No crash.

### Steps To Reproduce

Create an automation that selects input source from ATV

### Logs

```console
The logs (level 5) do not show anything.
```

### Configuration

```JSON
{
    "name": "ATV-Enhanced",
    "mediaTypes": [
        "music",
        "tv",
        "unknown",
        "video"
    ],
    "deviceStates": [
        "idle",
        "paused",
        "playing",
        "stopped"
    ],
    "deviceStateDelay": 1,
    "remoteKeysAsSwitch": [
        "down",
        "home",
        "left",
        "menu",
        "pause",
        "play",
        "right",
        "select",
        "turn_off",
        "turn_on",
        "top_menu",
        "up",
        "volume_down",
        "volume_up"
    ],
    "avadaKedavraAppAmount": 15,
    "customInputURIs": [
       "vlc://http://streams.abidingradio.org:7800/1"
    ],
    "disableVolumeControlRemote": false,
    "absoluteVolumeControl": false,
    "setTopBox": false,
    "discover": {
        "multicast": true,
        "unicast": [
            "192.168.1.112"
        ]
    },
    "forceVenvRecreate": false,
    "logLevel": 5,
    "updateCheckLevel": "stable",
    "updateCheckTime": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideAbsoluteVolumeControl": false,
            "absoluteVolumeControl": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "_bridge": {
        "username": "..."
    },
    "platform": "AppleTVEnhanced"
}
```

### Operating System: Distribution

RaspberryPi4

### Operating System: Distribution Version

12

### Homebridge Version

1.8.5

### Homebridge Config UI Version

4.64.0

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.10.1

### Node Version

22.11.0

### NPM Version

10.9.0

### Python Version

3.11.2

### PIP Version

23.0.1

### Audio Output

no

### Same Subnet

yes

**Comment by maxileith** [comment]
Bug not in scope of the plugin but the home app.

**Comment by ukiews** [comment]
I don't think it is a Home App issue, as selecting sources from my Vizio TV (Homekit) works fine.

**Comment by maxileith** [comment]
> @maxileith are you able to reproduce?

I have no Mac and cannot reproduce on iOS.

As a developer you don't have any influence on the behavior of the home app. If the home app crashes it is always a bug of the home app. Even if devices respond unexpectedly the app should do proper error handling.

In this exact case, the app does not even communicate with the device while setting up the automation. The home app is just very very buggy.

**Comment by robertying** [comment]
For anyone who's facing the same issue, I think I found a workaround.

Whenever you add a new scene (or automation but I haven't tested it) and add an accessory to the scene, the accessory will default to the currently selected input source. So if you are using this plugin and have the current Apple TV input as Netflix, go add a new scene and add the exposed Apple TV accessory, click the accessory icon if needed to make sure it's on, do not click the accessory name (which will try opening the source selection and crash the Home app), and then save the scene. Do some testing to make sure this scene correctly opens the desired app. Now just switch the current Apple TV input to a different one and repeat the process.
