### ISSUE TITLE
Issue with CEC Volume

### ISSUE THREAD

**Issue by Max3956** [maxileith/homebridge-appletv-enhanced#808]
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

I Recently Installed Apple TV Enhanced, and it all works great except for the, Absolute volume control (fan). The volume up and down switch (Which is going via CEC to my Receiver) works fine, but not the (fan) volume. Does anyone have some suggestions to get this working, Thanks 

### Logs

```console
none
```

### Configuration

```JSON
bash: config.json: command not found
```

### Operating System

Mac Os

### Operating System: Bits

64-bit

### Operating System: Distribution

Raspberry Pi

### Operating System: Distribution Version

12 (bookworm)

### Docker

no

### Docker Image

None

### Homebridge Version

v1.8.5

### Homebridge Config UI Version

v4.65.1

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

v1.10.2

### Node Version

v22.12.0

### NPM Version

10.5.0

### Python Version

3.11.2

### PIP Version

23.0.1

### HDMI Hops

I am going from the Apple TV to my Anthem Receiver, this is the device which volume is controlled

### Audio Output

no

### Same Subnet

yes

**Comment by maxileith** [comment]
Your receiver does not support absolute volume control via CEC.

Nevertheless, congrats on the receiver.
